### ISSUE TITLE
Matthews coeff., solvent content and number of copies in the ASU

### ISSUE THREAD

**Issue by FilomenoSanchez** [project-gemmi/gemmi#10]
Hi,
Thank you for this great package, I find it really useful. I was wondering if there is an easy way to find the matthews coefficient and the solvent content for a given mtz file (assuming we know the sequence). Basically I'm interested in estimating the number of copies in the ASU.
Thanks

**Comment by wojdyr** [comment]
Hi Filomeno

I did calculation of Matthews coef. from a PDB file as an exercise (it can be printed by "gemmi content"). To use MTZ + sequence we'd need to estimate molecular weight from the sequence.
I think the weights of amino-acids would need to be tabulated.
I have other things to finish this week, but I can look into it next week. If you're still interested next week let me know.

**Comment by FilomenoSanchez** [comment]
Yes I would be definitely interested in a function that estimates the cell content based on MTZ + molecular weight from the sequence. This would be very useful not just for me but also for some of the other people based with me at Liverpool working on MR pipelines.

**Comment by wojdyr** [comment]
I tabulated weights for 300+ most popular residues.
So you can calculated weight from the sequence, and further -- the Matthews coefficient and solvent content. Here is an example:
https://gemmi.readthedocs.io/en/latest/mol.html#sequence

**Comment by FilomenoSanchez** [comment]
@wojdyr thanks for the response. Would then gemmi predict how many copies in the asymmetric unit only with mtz+seq (without a pdb file)?

**Comment by wojdyr** [comment]
You can use Matthews coefficient to tell how many copies are possible / probable.

**Comment by FilomenoSanchez** [comment]
@wojdyr of course, sorry I misunderstood something (maybe reading too fast). Thanks again for the changes and the great package!
