### ISSUE TITLE
restraints info missing when reading a PDB (REMARK 3 section)

### ISSUE THREAD

**Issue by xvlaurent** [project-gemmi/gemmi#108]
Hello,

I noticed that mmCIF header category _refine_ls_restr is empty even if the source PDB file have corresponding info in it REMARK 3 section (for example: 5i55, 1a5m).

The python code I used to import and check the info:

```
import gemmi
structure = gemmi.read_structure(PDB_Path)
block = structure.make_mmcif_headers()
block.get_mmcif_category('_refine_ls_restr.')
```

I also tried to use the  _convert_ function to convert PDB to mmcif, but this category is not in the resulting file.

Thanks by advance.

**Comment by wojdyr** [comment]
Each of the refinement programs has different format of restraint statistics in REMARK 3.
REMARK 3 doesn't even have a unified format – it's [documented by the PDB][1] separately for each program.
Gemmi can populate `_refine_ls_restr` from PDB files outputted by BUSTER, but probably not from different programs.

Why do you need it?

[1]: https://www.wwpdb.org/documentation/file-format-content/format33/remark3.html

**Comment by xvlaurent** [comment]
I want those info to make them accessible in a graphical interface.

I didn't know that only REMARKS 3 from files outputted by BUSTER where fully parsed.
I understand that it will be a pain to support more so I can try to fill this the best I can with a bunch of regular expression for files from other software.
