### ISSUE TITLE
Better parsing of spacegroup information

### ISSUE THREAD

**Issue by orex** [project-gemmi/gemmi#117]
Dear Gemmi developers,

Thank you very much for you library. It is really useful for parsing cif files. But as many other codes (like ex. openbabel) the code can't parse correctly some spacegroups (P 2/m, monoclinic) because of ambiguity. The symmetry operations depends on axis configuration: which angle (alpha, beta or gamma) is not equal pi/2.
The example here
https://github.com/orex/supercell/blob/version2/data/examples/synth_complex/supercheck.cif

I wrote a code which can check if a `gemmi::SpaceGroup` corresponds to the unitcell, and change it if needed.

https://github.com/orex/supercell/blob/f73ce76590085a9839f23c247142edef38325aeb/src/core/cif_io.cpp#L79
Functions `verify_sg_uc_compatibility` and `resolve_sg_by_uc`.

If you are interested in, you can use it in gemmi under any license. From my opinion it will be better to modify the function
`find_spacegroup_by_name` and add not only angles, but all the unitcell there.

From my point of view, it will be super useful to have a function
`find_spacegroup_by_parameters(<unitcell>, <sg number> (-1 if not exists), <H-M name>, <Hall name>, <symmetry ops>, <output warning message>)` which can find the structure by all existen information and produce a warning string with inconsistencies.  

Best,
Kirill.

**Comment by wojdyr** [comment]
Hi Kirill,

full spacegroup names in SG 10 are:
P 1 2/m 1
P 1 1 2/m
P 2/m 1 1

"P 2/m" is understood as a shortcut for the first. I don't know if it's widely used to mean other settings. Usually, it's preferable to choose unit cell with alpha = gamma = 90.

It'd be fairly easy to check if space group names are consistent with operations from `_space_group_symop_operation_xyz`: you could either use `find_spacegroup_by_ops()` and compare obtained `SpaceGroup`, or compare the operations.
Perhaps in your case it's more reliable to just use operations from the CIF file?

Your function that checks the compatibility of unit cell and space group is a good idea. Now I'm focused on other things, but I'll get back to it at some point.

**Comment by orex** [comment]
Hi Marcin,

Of course, if you have proper cif file you have nothing to worry about. But many files in COD are messy. Using symmetry operations was my first idea, because I don't care about symmetry of the system, I just need to convert it to P1 and after I'm using my algorithms for symmetry search, which are pure mathematical. But ... I've checked some structures and realize that the symmetries operations are wrong in half of the cases. I was surprised))))

As for `find_spacegroup_by_ops`, I did not find a function which use "pure" symmetries to find SG. The function needs `GroupOps` therefore, as I understand, I need take symmetries from a cif file and convert it to the representation (split to symmetries and translations), which is probably more complex, than a way back. Just guess some SG and verify it with the direct symmetries from cif file. 

Best,
Kirill.

**Comment by keitaroyam** [comment]
@wojdyr Currently `SmallStructure` can only have `spacegroup_hm`, but isn't it more useful to have `SpaceGroup` object?

**Comment by wojdyr** [comment]
It has method `find_spacegroup()` that returns `SpaceGroup` object.
The same with `Structure`.

**Comment by keitaroyam** [comment]
Yes, but it is based on `spacegroup_hm`. All non-regular settings are covered?

**Comment by wojdyr** [comment]
No. Would a function such as find_spacegroup_from_equiv_pos() help?

@orex I didn't address your last comment. No need to split symmetries and translations. It works like this:

```pycon
>>> op_list = ['x,y,z', 'x,-y,z+1/2', 'x+1/2,y+1/2,z', 'x+1/2,-y+1/2,z+1/2']
>>> gops = gemmi.GroupOps([gemmi.Op(o) for o in op_list])
>>> gemmi.find_spacegroup_by_ops(gops)
<gemmi.SpaceGroup("C 1 c 1")>
```

**Comment by wojdyr** [comment]
On the other hand, settings that aren't tabulated in `symmetry.hpp` won't work anyway. So the only advantage is that determining space group from the operations can be more reliable.

**Comment by orex** [comment]
Hi @wojdyr! 
To be honest I don't remember why I exactly wrote the statement. 1) Probably because the code is not so transparent in C++ as Python code above. Can you rewrite the code in C++ in a state-of-art way? For the future references.
2) Or may be because of in time of our discussion `x/2+1/2` parsing was not available. I've check the current code, you changed the function `parse_triplet_part` after our discussion to support this.
Anyhow, the real problem is that I've checked SOD and it looks like that in 20-30% of problematic structures (monoclinic, H<->R) does not have a consistency in the structure definition: `Unit cell` vs `symmetry ops` vs  `Hall` vs `HM` vs `SG number`. Therefore I just took the HM if exists and correct it with cell parameters.

It is beyond my project to do a careful verbose check of the input structures. I did MVP to support very basic cases, but still it is covers around 70% (my private estimation, no science) of the issues I had. But of course, it can hide an existing problems.
Your project is great! It is exactly what I need in my program. Previously I used OpenBabel, but it was too heavy and not flexible at all. With your interface, I have a good tooling + full control on process. But, I think that everybody from inorganic world will say you a huge thanks, if you implement an additional functionality of deep and verbose analysis of input symmetry as I describe in first message. Wyckoff and multiplicity can also be included. I think that more than half of issues that users address to my program are because of such problems in input file.

P.S. To your last comment. Ones more, symmetries look quite unreliable.

**Comment by keitaroyam** [comment]
@wojdyr That makes sense. I now noticed that ext (like ":2") can be passed to `gemmi.SpaceGroup` and I hope it would work for most cases. It may be better to have `gemmi.GroupOps` instead of space group (and make a function like `set_cell_images_from_groupops`), but it is not absolutely needed at the moment.

**Comment by wojdyr** [comment]
@keitaroyam it could be added if it turns out to be necessary. Also, I could add more tabulated entries.
But I wouldn't go for general handling of space groups, as it is done in cctbx, where any space group setting can be used.

@orex In C++ it's a separate function instead of GroupOps constructor:

    GroupOps split_centering_vectors(const std::vector<Op>& ops)

As for a function that checks consistency of all symmetry-related data, it's a lot of decision making what to do when things are inconsistent. I imagine that reliability of different fields depend on the software that generates them. For example, files for SHELX and Olex2 have such a comment:
```
_shelx_space_group_comment
;
The symmetry employed for this shelxl refinement is uniquely defined
by the following loop, which should always be used as a source of
symmetry information in preference to the above space-group names.
They are only intended as comments.
;
```
In files from the PDB the H-M name is reliable if cell angles are used for disambiguation of trigonal and hexagonal settings. With one exception: gemmi doesn't understand `C 4 21 2` which is used in two entries but is probably an incorrect name.

**Comment by orex** [comment]
`split_centering_vectors` sounds very confusing. It was difficult for me to assume that it can do the job. 

Of course, such decision is tricky to make, but "shortcuts" and "red flags" can be estimated:
1) Cell shape can be a reference. If SG is not "fit" to cell, it is a error no doubt.
2) SG number can also be a reference. If it not the same as SG from name, it is a error.
3) If SG number provided, and `const SpaceGroup Tables_<Dummy>` has only one SG for this number, the rest info can be ignored.
4) If multiplicity of atoms is not consistent with position in the SG - error.
etc.

And, of course, warning message can help user to identify the problem.

I agree, that it is difficult to make a perfect solution. Most probably it is not achievable. But it is possible to create a good solution which can help people. My solution that I proposed and am using, is very far from perfect, but it helps a lot, at least to my users.

**Comment by wojdyr** [comment]
> `split_centering_vectors` sounds very confusing. It was difficult for me to assume that it can do the job.

Indeed. Would `make_groupops_from_ops` be better?

BTW some time ago I added `UnitCell::is_compatible_with_spacegroup()` and `UnitCell::is_compatible_with_groupops()` for checking consistency between cell parameters and space group.

**Comment by orex** [comment]
Your code probably is the most clear and well structured "scientific" code which I ever saw. Therefore, probably, you have a strong reasons behind to name the function in such way. The new name of the function it sounds quite useless. In general it just repeat the input and output of the function which you can read from argument and return value in function definition. The previous name is better, because it hints the functionality of the function. But not an "application"))) My problem is that it is not obvious from the first point of view, that it is exactly that converting I need to do. Now, just having your input, I found it quite obvious. 

I suggest to do a trivial function like `gemmi::SpaceGroup *  spacegroup_from_symmetries_strings(const std::vector<string> &s)`, which return nullptr in case of error. Probably not so much people will use the function itself, but checking the code inside it, can give full information about converting string triplets to SpaceGroup, thus no other function need to be renamed. This is a reference implementation I mention early. I was working with your code exactly in the same way. Took "small molecule", understood that it is not what I need, and extract the patterns inside to my function. Unfortunately that time there was no such patterns and it rise the questions.

`UnitCell::is_compatible_with_groupops()` looks super similar to my code I proposed half year ago (although `array<double, 6>` is confusing for me for a very fast first look): https://github.com/orex/supercell/blob/f73ce76590085a9839f23c247142edef38325aeb/src/core/cif_io.cpp#L79. Therefore my proposition which fix SG shrinks to 12 lines of code https://github.com/orex/supercell/blob/f73ce76590085a9839f23c247142edef38325aeb/src/core/cif_io.cpp#L96
