### ISSUE TITLE
Segment ID in mmcif

### ISSUE THREAD

**Issue by keitaroyam** [project-gemmi/gemmi#118]
I want to save Structure in mmcif and pdb format, after `st.expand_ncs(gemmi.HowToNameCopiedChain.Dup)`, which puts operator IDs to `residue.segment`.

It seems `residue.segment` is not written to mmcif file. PyMOL reads `_atom_site.label_asym_id` as segment ID, but it is treated as `residue.subchain` in gemmi, and copying `residue.segment` to `residue.subchain` will result in a failure when writing mmcif file.

Is there any way to write `residue.segment` to mmcif file? Alternatively `st.expand_ncs(gemmi.HowToNameCopiedChain.Dup)` should put operator IDs to anywhere else?

**Comment by wojdyr** [comment]
what is the failure when writing mmcif file?
I tried this and it works (although I didn't check the output file):
```py
import gemmi

st = gemmi.read_structure('tests/5cvz_final.pdb')
st.setup_entities()
st.expand_ncs(gemmi.HowToNameCopiedChain.Dup)
for model in st:
    for chain in model:
        for res in chain:
            res.subchain = res.segment
st.make_mmcif_document().write_file('out.cif')
```

**Comment by keitaroyam** [comment]
If I tried your example with 5cvz.pdb from PDB, the error occurred:
```py
Traceback (most recent call last):
  File "tst.py", line 11, in <module>
    st.make_mmcif_document().write_file('out.cif')
IndexError: auth_seq_id_to_label(): empty span
```
It was ok with 5cvz.cif and tests/5cvz_final.pdb. Could you try the file from PDB?

**Comment by wojdyr** [comment]
The problem was in writing equivalent of DBREF in mmCIF – I tried to catch wrong exception.

This problem should be fixed now (mmcif can be written), but another problem is that subchain names are referenced in a couple places and when you change it in Residue the metadata is not consistent. I'll think what to do with it tomorrow.

**Comment by keitaroyam** [comment]
Thank you! The error was gone with 58e6395.

**Comment by wojdyr** [comment]
After looking into it, I'll leave it as it is now.

To keep things consistent `Entity::subchains` would need to be changed manually, but it seems that usually this consistency is not important. If changing `subchain` was more common, perhaps we could have a function for it.

**Comment by keitaroyam** [comment]
That is fine with me. Thank you.
