### ISSUE TITLE
Grid.interpolate_value crashes Python

### ISSUE THREAD

**Issue by biochem-fan** [project-gemmi/gemmi#12]
Hi, I noticed that the following program causes segmentation fault in Python 3.6.4.

```python
import gemmi

fn_mtz = "4MAA_map_coeffs.mtz"

mtz = gemmi.read_mtz_file(fn_mtz)
grid = mtz.get_f_phi_on_grid('2Fo-Fc', 'PH2Fo-Fc', mtz.get_size_for_hkl(sample_rate=3.0))

real_space = gemmi.transform_f_phi_grid_to_map(grid)
coord = gemmi.Position(0, 7.57895, 56.0842)
print(real_space.interpolate_value(coord))
```

The problematic MTZ file was created as:
```
phenix.fetch_pdb --mtz 4MAA
phenix.maps reflection_data.file_name=4MAA.mtz 4MAA.pdb map_coefficients.map_type=2Fo-Fc
```
It is available here: https://drive.google.com/open?id=1p87TDu4n9N15EVljGGu8U1YbunefEOmj

**Comment by wojdyr** [comment]
Thanks for reporting it. Somehow I didn't implement special handling of points near the faces of the unit cell. Hopefully now it's correct.

**Comment by wojdyr** [comment]
@biochem-fan just to let you know: interpolate_value() was reported to be too slow when used from Python for a large number of points. We are testing now interpolate_values() (with s at the end) that interpolates values on a regular grid and puts results into numpy array.
I just documented it at https://gemmi.readthedocs.io/en/latest/grid.html

**Comment by biochem-fan** [comment]
Great! For my purpose the speed of `interpolate_value()` was acceptable, but further speedup is of course welcome.
