### ISSUE TITLE
add python bindings for adding hydrogens to a cif file?

### ISSUE THREAD

**Issue by danny305** [project-gemmi/gemmi#120]
I don't think there are python bindings for adding hydrogens to the `ATOM` and/or 'HETATM' in a cif file?

This would be super great feature if it doesn't already exist.

**Comment by keitaroyam** [comment]
It can be done using `gemmi.topology`.
https://gemmi.readthedocs.io/en/latest/analysis.html#topology

**Comment by wojdyr** [comment]
@danny305 is this what you were looking for?

**Comment by danny305** [comment]
I have never played with topology which is probably why I didn't see that.

It seems like the input is a gemmi.Structure, which I can make from a cif file. 

Is there a cif version of the monomer library? In the example it uses the CCP4 monomer library.

**Comment by wojdyr** [comment]
The CCP4 monomer library is a large number of CIF files. It contains restraints that are used to position hydrogen atoms.

Actually I don't know what you had in mind when you wrote about adding hydrogen atoms to `ATOM` or `HETATM`.

**Comment by danny305** [comment]
What I meant is could we add hydrogen atoms to the atom_site category in a cif file. 

So add hydrogens to the protein/DNA (`ATOM`) and ligands and water (`HETATM`).

Does this topology route lead to a cif file with added hydrogen rows in the atom_site category?

**Comment by wojdyr** [comment]
atom_site category etc are technicalities.
The most important question is to what atoms the hydrogens are to be added and at what positions.
Gemmi adds hydrogens according to rules in a monomer library.

Another (more popular) way to add hydrogens is this program from Richardson lab:
http://kinemage.biochem.duke.edu/software/reduce.php
I suppose there are also other programs, but I've never researched it.
