### ISSUE TITLE
segment ID and LINK

### ISSUE THREAD

**Issue by keitaroyam** [project-gemmi/gemmi#121]
When writing pdb (and mmcif) file, LINKs are written only when the residues are "found" in the model. 
https://github.com/project-gemmi/gemmi/blob/023ab6a637f5fd9aa492677123e7fd4662245e8d/include/gemmi/to_pdb.hpp#L590

This does not work if the residue has non-empty segment ID, because `find_residue()` and `find_cra()` check `residue.segment` through `ResidueId::matches()`.
https://github.com/project-gemmi/gemmi/blob/023ab6a637f5fd9aa492677123e7fd4662245e8d/include/gemmi/seqid.hpp#L94

The LINK(R) record does not have a field of segment ID, so `residue.segment` should be ignored when matching?

**Comment by wojdyr** [comment]
Yes, that's right. I just added to `find_cra()` an optional argument `ignore_segment`, and used it when writing LINK and SSBOND. Segments haven't been really tested much, so you may come across other problems.
These changes I just pushed also hasn't been tested much.

**Comment by keitaroyam** [comment]
Thank you! It worked. I will let you know if I found any problems.
