### ISSUE TITLE
Position from mark.pos() occasionally differs from mark.to_cra(st[0]).atom.pos

### ISSUE THREAD

**Issue by cbalbin-FIU** [project-gemmi/gemmi#125]
Hey,

First off, thanks for this amazing library. It is the most well thought out and well documented library for structural biology I've seen.

I am facing an issue where the distance between two atoms differs depending on what method I use to grab an atoms position.

Sample code to reproduce issue
```python3
import gemmi 

st = gemmi.read_structure("1w4r.cif")

ns = gemmi.NeighborSearch(st[0], st.cell, 4)

# adding only CYS-SG atoms to ns
for n_ch, chain in enumerate(st[0]):
    for n_res, res in enumerate(chain):
        if res.name == "CYS":
            for n_atom, atom in enumerate(res):
                if atom.name == "SG":
                    ns.add_atom(atom, n_ch, n_res, n_atom)



# searching for CYS-SG from LYS-NZ atoms
for chain in st[0]:
    for res in chain:
        if res.name == "LYS":
            for atom in res:
                if atom.name == "NZ":
                    marks = ns.find_neighbors(atom, min_dist=0.25, max_dist=4)
                    for mark in marks:

                        cra = mark.to_cra(st[0])


                        # notice that the position from mark.pos() differs from that of mark.to_cra(st[0]).atom.pos
                        pos_from_mark = mark.pos()
                        pos_from_cra = mark.to_cra(st[0]).atom.pos
                        print(f"pos from mark: {pos_from_mark}")
                        print(f"pos from cra: {pos_from_cra}")
                        print(((chain.name, res.name, res.seqid.num, atom.name, atom.occ),(cra.chain.name, cra.residue.name, cra.residue.seqid.num, cra.atom.name, cra.atom.occ),(ns.dist(pos_from_mark, atom.pos), ns.dist(pos_from_cra, atom.pos))))
                        print()
                        print()
```

Output from sample code (I am only displaying one example here for brevity, full output at the end)

```text
pos from mark: <gemmi.Position(155.666, 89.284, 2.037)>
pos from cra: <gemmi.Position(1.83, 89.284, -2.037)>
(('C', 'LYS', 57, 'NZ', 1.0), ('C', 'CYS', 79, 'SG', 1.0), (2.6172618865966797, 4.964349269866943))

...
```
Notice that the position for the same atom differs depending on the method used to access it. This only occurs sometimes. I believe the postion obtained from mark.to_cra(st[0]).atom.pos is the correct position (at least it matches with that in the cif file). 

Now looking at the positions, I'm thinking maybe a symmetry operation was applied. 
Does the NeighborSearch operate only on the asymetric unit or does it apply any symmetry operations to generate an entire unit cell or biological assembly? If so, is there a way to only search within the asymetric unit?

When using the mark.pos() in the ns.dist calculation I get a distance between these atoms of 2.62 Å, where as when using the mark.to_cra(st[0]).atom.pos I get a distance of 4.96 Å. I believe 4.96 Å is the "true" distance (It matches the distance computed by pymol).

If something is unclear or I am doing something wrong, please let me know.

Thanks!

Full output
```text
pos from mark: <gemmi.Position(155.666, 89.284, 2.037)>
pos from cra: <gemmi.Position(1.83, 89.284, -2.037)>
(('C', 'LYS', 57, 'NZ', 1.0), ('C', 'CYS', 79, 'SG', 1.0), (2.6172618865966797, 4.964349269866943))


pos from mark: <gemmi.Position(-41.0837, 76.495, 62.202)>
pos from cra: <gemmi.Position(33.013, 76.495, -26.103)>
(('D', 'LYS', 191, 'NZ', 1.0), ('D', 'CYS', 188, 'SG', 1.0), (3.3911373615264893, 3.391136407852173))


pos from mark: <gemmi.Position(-16.936, 86.328, 60.581)>
pos from cra: <gemmi.Position(-16.936, 86.328, 60.581)>
(('F', 'LYS', 57, 'NZ', 1.0), ('F', 'CYS', 79, 'SG', 0.3499999940395355), (3.035417318344116, 3.0354197025299072))


pos from mark: <gemmi.Position(21.082, 37.3, 37.886)>
pos from cra: <gemmi.Position(21.082, 37.3, 37.886)>
(('H', 'LYS', 57, 'NZ', 1.0), ('H', 'CYS', 79, 'SG', 1.0), (3.2843642234802246, 3.284363269805908))
```

**Comment by wojdyr** [comment]
Hi,
NeighborSearch searches for atoms in the crystal (if it's a crystal, i.e. if the unit cell is set).
It doesn't generate the entire unit cell, but it works like it did, except that it can find atoms also in other unit cells.

In your case, you indeed find an atom from a different ASU. The original atom from the same ASU is beyond the search radius (4.96A) but you find one of its symmetric images that's in distance 2.62A.
You can check `mark.image_idx` – if it's non-zero then a symmetry operation was used.

To limit the search to the ASU you could remove the unit cell information: 

    st = gemmi.read_structure("1w4r.cif")
    st.cell = gemmi.UnitCell()

**Comment by cbalbin-FIU** [comment]
Thanks! This was very helpful (:
