### ISSUE TITLE
const Document acces

### ISSUE THREAD

**Issue by danpf** [project-gemmi/gemmi#129]
Hello,
I was just trying out this library and I found it strange that Block::find is not const. Is there a design reason for that?
thanks, ~Dan

**Comment by wojdyr** [comment]
Hi Dan,
it's because the result (`Table`) can be used to modify Block.

**Comment by danpf** [comment]
i see -- it doesn't seem like that would be easy to change either :/
is this something you might be open to changing in the future or is this your preferred implementation?

**Comment by wojdyr** [comment]
Things may change in the future, but currently I'd rather not do it.
I'm also missing such a const function and I'm using `const_cast` in a few places, but we'd need to have separate ConstTable class for this, which seems excessive to me. The whole const-correctness is already taking too much time to maintain.
