### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by keitaroyam** [project-gemmi/gemmi#133]
If I use gcc from homebrew, `python3 setup.py build` fails with
```sh
gcc: error: unrecognized command-line option '-stdlib=libc++'
```

I always remove this if-block not to give `-stdlib=libc++`,  but it would be more convenient for everyone if setup.py takes care of this. Could you look into it?
https://github.com/project-gemmi/gemmi/blob/656ddb834c9450eb5e3eeac17c103ede3b474611/setup.py#L107-L108

I am using macOS Catalina with gcc version 10.2.0 (Homebrew GCC 10.2.0_4).

**Comment by wojdyr** [comment]
I can't test it on Mac now, but I modified setup.py copying various changes from python_example/setup.py.
If it still doesn't work, you could try setting the environment variable ARCHFLAGS, as per this comment:
https://github.com/pybind/python_example/issues/70#issuecomment-802835715

**Comment by wojdyr** [comment]
no, actually it can't help if gcc doesn't recognized the option. I'll look into it again.

**Comment by wojdyr** [comment]
ok, now it should be fixed

**Comment by keitaroyam** [comment]
Thank you! It worked for me and my colleagues.
