### ISSUE TITLE
gemmi validate ignores "_chem_comp_tor.period"?

### ISSUE THREAD

**Issue by CV-GPhL** [project-gemmi/gemmi#134]
It seems that the extra checks triggered by -M are not aware of the periodicity of a torsion restraint. I.e. having

```
loop_
_chem_comp_tor.comp_id               
_chem_comp_tor.id                    
_chem_comp_tor.atom_id_1             
_chem_comp_tor.atom_id_2             
_chem_comp_tor.atom_id_3             
_chem_comp_tor.atom_id_4             
_chem_comp_tor.value_angle           
_chem_comp_tor.value_angle_esd       
_chem_comp_tor.period                            
U3V       3fold-27 H32 C22 C20 C21 180.0      15.0  3
```
gives a message
```
U3V [atom.xyz] torsion H32-C22-C20-C21 should be 180 (esd 15) but is 60.13
```
But periodicity of 3 means that the torsion can be 180, 300 or 420 (=60).

----
Also: maybe the help message should be changed from
```
  -m, --monomer   Extra checks for Refmac dictionary files.
```
to
```
  -m, --monomer   Extra checks for mmCIF restraints dictionary files.
```
The majority of content in those restraints dictionaries is standard mmCIF syntax - even if various refinement programs add their own, non-standard extensions.

**Comment by wojdyr** [comment]
Ok should be fixed now.

Regarding the help message, I'd need to check how the mmCIF variant differs from what CCP4 uses.
Is any software using the restraints as described in the mmCIF spec?

**Comment by CV-GPhL** [comment]
Hi Marcin,

On Thu, Jul 08, 2021 at 07:41:39AM -0700, Marcin Wojdyr wrote:
> Regarding the help message, I'd need to check how the mmCIF variant differs from what CCP4 uses.
> Is any software using the restraints as described in the mmCIF spec?

There is no true mmCIF restraints variant (so noone is using it in its
clear form) - but there is no real and single REFMAC/CCP4 variant
either: over the years multiple incarnations have been floating
around and developed.

However, there is a core set of categories/items (not strictly
speaking mmCIF) that is shared between REFMAC, Phenix and BUSTER that
means that restraints from Grade, AceDRG or Elbow can be used by all
those programs (and presumably also Coot). Ideally, the items
differing from the actual mmCIF dictionary should be namespaced via
something like e.g. "ccp4_", "gphl_" or "phenix_".

Of course, if you tested that feature only against REFMAC/CCP4
dictionaries (of what version/specification? Only from AceDRG
onwards?) the help message might still be correct. If you need
examples from e.g. Grade: you can obviously generate those on the
Grade webserver or I can send you a large selection if needed.

Cheers

Clemens

-- 

*--------------------------------------------------------------
* Clemens Vonrhein, Ph.D.     vonrhein AT GlobalPhasing DOT com
* Global Phasing Ltd., Sheraton House, Castle Park 
* Cambridge CB3 0AX, UK                   www.globalphasing.com
*--------------------------------------------------------------

**Comment by wojdyr** [comment]
Hi Clemens,
I implemented reading monomers by analyzing how monomers (and also links and modifications) look like in the ccp4 monomer library.
I don't know how mmCIF differs. I see that, for example, it doesn't have `_chem_comp_tor.period`, but instead it uses a separate category `_chem_comp_tor_value`. Are there any programs that use it?

**Comment by CV-GPhL** [comment]
Hi Marcin,

On Mon, Jul 12, 2021 at 02:02:55AM -0700, Marcin Wojdyr wrote:
> I implemented reading monomers by analyzing how monomers (and also links and modifications) look like in the ccp4 monomer library.

Good idea, yes. Since all major MX refinement programs can generate
dictionaries that other programs can understand and read those from
other packages as well, it might make sense to extend this across more
packages (like Grade from Global Phasing etc).

> I don't know how mmCIF differs. I see that, for example, it doesn't
> have `_chem_comp_tor.period`, but instead it uses a separate
> category `_chem_comp_tor_value`. Are there any programs that use it?

There are no (MX) programs as far as I know that use a completely
valid mmCIF file as a restraints dictionary. So the mmCIF dictionary
needs to be extended to mirror the current practice, yes. At the same
time, we need to collect what the main restraint dictionary providers
(generators) and users (refinement programs) are creating and using.

We will most likely not change the restraint dictionaries to follow
the mmCIF dictionary, but rather the other way round. If Gemmi could
already validate

  (1) those categories/items that are in mmCIF and generated/used by
      MX restraint dictionary providers/programs

  (2) those categories/items that are not in mmCIF but are
      generated/used by all restraint dictionaries dictionary
      providers/programs

  (3) those categories/items that are specific to a particular
      restraint dictionaries generator

it would provide a clearer picture what is already in mmCIF (or might
only need an alias), what is commonly accepted and used "in the wild"
and finally what is specific to a given generator (like Grade, AceDRG
or Elbow ... there are others/more).

Cheers

Clemens

**Comment by wojdyr** [comment]
You can validate anything if you provide a corresponding dictionary.

    gemmi validate -d file.dic file.cif

But probably only a dictionary for mmCIF exists.
The format used by Refmac is described in a paper:
http://scripts.iucr.org/cgi-bin/paper?S0907444904023510

That's also the format used by AceDRG.
For Grade, BUSTER, PHENIX and other programs - you could ask developers what restraint formats they read/write.
