### ISSUE TITLE
Save the biological assembly in a cif format

### ISSUE THREAD

**Issue by IkramMHD** [project-gemmi/gemmi#135]
Hi @wojdyr, 
thank you for the cif parser, 

I 'm actually coding in python and i want to generate the biological assembly, my first question is how do you generate the biological assemby( i want to pic the author defined assembly) is there any way to acess to theese informarmation in gemmi allowing us to chosse the model that correspond to the author defined assembly?
The second question is once the assembly generated, i want to save it in cif fomat however i having an eroor 'gemmi.Model' object has no attribute 'make_mmcif_document, 
also tried the write_file method, same error 'gemmi.Model' object has no attribute 'write_file'.

**Comment by wojdyr** [comment]
Assembly has property `author_determined`. I just added Python bindings to it:
https://gemmi.readthedocs.io/en/latest/mol.html#assembly

`make_mmcif_document` is a method of Structure (not Model).
