### ISSUE TITLE
Tests fail on i386 architecture

### ISSUE THREAD

**Issue by merkys** [project-gemmi/gemmi#136]
I have packaged gemmi for inclusion into Debian. It builds successfully in all Debian-supported architectures except somewhat obsolete i386 ([full build log](https://buildd.debian.org/status/fetch.php?pkg=gemmi&arch=i386&ver=0.4.5%2Bds-1&stamp=1629138531&raw=0)):
```
make  -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
make[5]: Entering directory '/<<PKGBUILDDIR>>/obj-i686-linux-gnu'
/usr/bin/ctest -C None
Test project /<<PKGBUILDDIR>>/obj-i686-linux-gnu
    Start 1: cpptest
1/1 Test #1: cpptest ..........................***Failed    0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.01 sec

The following tests FAILED:
	  1 - cpptest (Failed)
Errors while running CTest
```
I have an old i386 machine somewhere and could help debugging the situation, but I need directions on how to run tests in more verbose mode.

**Comment by wojdyr** [comment]
Thanks for the packaging work. You could run this test directly without ctest:

    ./cpptest

You could also update to version 0.4.7 (in the log file I see it's 0.4.5).

**Comment by merkys** [comment]
I have updated to 0.4.7 yesterday, but the problem on i386 [persists](https://buildd.debian.org/status/fetch.php?pkg=gemmi&arch=i386&ver=0.4.7%2Bds-1&stamp=1629696131&raw=0). I will try debugging on i386 whenever I find time, thank you for directions.

**Comment by wojdyr** [comment]
I cross-compiled it on 64-bit Ubuntu with i686-linux-gnu-g++-10 and I see the problem now.
It's nothing serious, it's the test itself that needs to be fixed. I'll fix it soon.

**Comment by merkys** [comment]
Great, thanks!
