### ISSUE TITLE
[Feature Request] FFT resolution parameter for mtz.transform_f_phi_to_map  

### ISSUE THREAD

**Issue by ConorFWild** [project-gemmi/gemmi#14]
Image processing real space density for many datasets is much easier when they are sampled to the same grid, but currently there is no easy way to do this that I can find: transform_f_phi_to_map often errors when given an exact size that is too small, and there isn't an easy way to find out what grid a map _would_ bee fft'd to anyhow. 

Also, because sometimes their preferred size is large, so being able to fft to the lowest common resolution would be helpful anyway when dealing with many datasets!

PanDDA in particular relies heavily on truncating datasets down to the lowest common resolution for its event finding, so this would be useful there!

**Comment by wojdyr** [comment]
transform_f_phi_to_map is indeed checking if all the data fits into the grid.
I guess it'd be better to ignore the reflections that are outside. I'll change it.

Limiting the resolution is also often useful, I'll add it somewhere.

The result from both will be different. The resolution cut-off will be spherical; ignoring points that don't fit on the grid will result in a better resolution along body diagonals.

I'll try to do both. I was going to do it today, but I got distracted by other things.

**Comment by wojdyr** [comment]
I made the first change and now if the specified grid size is too small `transform_f_phi_to_map` will ignore the reflections that are outside.
I plan to add a few more features to the grids, so I'll be changing things in the coming days.
I'll let you know when all is ready and tested.

**Comment by wojdyr** [comment]
One way to limit the resolution is to remove high-resolution data from the Mtz object.
Here is an example (2.0 is the resolution limit):

```python
mtz = gemmi.read_mtz_file('tests/5e5z.mtz')
all_data = numpy.array(mtz, copy=False)
mtz.set_data(all_data[mtz.make_d_array() >= 2.0])
```
Would this work?

**Comment by ConorFWild** [comment]
Yeah, I think that would work for my case!
