### ISSUE TITLE
Gemmi_Nucleotide

### ISSUE THREAD

**Issue by IkramMHD** [project-gemmi/gemmi#141]
Hello, 

I'm writing you again because i have new issues i'm using this code 

```
> file_gemmi= gemmi.read_structure(file.cif)
> assembly=gemmi.make_assembly(file_gemmi.assemblies[0], file_gemmi[0], gemmi.HowToNameCopiedChain.AddNumber)
> groups = gemmi.MmcifOutputGroups(True)  
> groups.group_pdb = True 
> file_gemmi.add_model(assembly, pos=0)
> del file_gemmi[1:] 
> file_gemmi.make_mmcif_document(groups).write_file(file)
```

So  it worked for a lot of structures but in some cases for exemple 1c9s and 2zuf,4BBL no nucleotide were found in the structures do you know how this can be explained and how can i resolve the problem.

Thank you

**Comment by wojdyr** [comment]
Did you find the problem?

**Comment by IkramMHD** [comment]
Hello,

Sorry for my late response, actually it not gemmi issues when i chek on the biological assembly designed by the author on the pdb, they actuaaly don't contains the RNA.

Thank's
