### ISSUE TITLE
Cs.ignore

### ISSUE THREAD

**Issue by IkramMHD** [project-gemmi/gemmi#146]
Hello,

I'm writing you because i have an issue with contact search, when i try to ignore same chain using contact search i keep having in the result object all the contact within same chain or same residue.
```
cs = gemmi.ContactSearch(5.0)
cs.ignore = gemmi.ContactSearch.Ignore.SameChain
 cs.ignore = gemmi.ContactSearch.Ignore.SameResidue
```
Thank you

**Comment by wojdyr** [comment]
How to reproduce it?
I just added a test -- with `gemmi.ContactSearch.Ignore.SameChain` I don't get contacts within the same chain.
