### ISSUE TITLE
List of categories in block

### ISSUE THREAD

**Issue by otienoanyango** [project-gemmi/gemmi#16]
Is it possible to get a list of categories in a block without looping? This is not so much a must have as it is a convenience function. 

Use case: was trying to add a unit test for a function that removes categories and wanted to see categories before and after and confirm all the categories in the list have been removed. I had to use a list comprehension but thought it should be useful enough to have a convenience function

**Comment by wojdyr** [comment]
If names of categories are sufficient for this, you could use
block.get_mmcif_category_names()

**Comment by otienoanyango** [comment]
Thank you. missed that
