### ISSUE TITLE
Question: Write SmallStructure to file

### ISSUE THREAD

**Issue by callumjd** [project-gemmi/gemmi#165]
I'm new to working with cif files but I really like gemmi. I have a simple question - I have created a new gemmi.SmallStructure(). I'd now like to write this to a cif file. I can't find any examples, and don't seem to be able to convert SmallStructure to a Block or Document. Any tips?

**Comment by wojdyr** [comment]
I'm afraid it's not implemented.
I don't remember why SmallStructure was implemented a couple years ago, but from what I remember no-one has asked about writing it to a file before.
I'll leave this issue open as a feature request.

**Comment by callumjd** [comment]
Thank you for the quick response. I will look into other options.
Since I'm still learning my way around gemmi, is it possible to do this some other way? A short example of what I'm trying to do:

`# create SmallStructure
st=gemmi.SmallStructure()
st.spacegroup_hm=gemmi.find_spacegroup_by_number(4).hm
st.cell=gemmi.UnitCell(7.0,10.0,10.0,90,110,90)
st.setup_cell_images()
        
# add a site
site=gemmi.SmallStructure.Site()
site.fract=st.cell.fractionalize(gemmi.Position(1.0,2.0,1.0))
site.label='C1'
site.element=gemmi.Element('C')
site.occ=1
st.add_site(site)

# output
# st.write_file('new_st.cif')
`

**Comment by wojdyr** [comment]
I'm afraid not, the only other way is to not use gemmi.
I'll implement it soon – it's relatively simple.

**Comment by wojdyr** [comment]
I implemented writing a minimal cif file. The last line will be:

    st.make_cif_block().write_file('new_st.cif')

and you also need to set name that will be used for the CIF block:

     st.name = 'abcd'

The result then is:
```
data_abcd
_cell_length_a 7
_cell_length_b 10
_cell_length_c 10
_cell_angle_alpha 90
_cell_angle_beta 110
_cell_angle_gamma 90
_symmetry_space_group_name_H-M 'P 1 21 1'

loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_U_iso_or_equiv
_atom_site_occupancy
_atom_site_disorder_group
C1 C 0.194852891 0.2 0.106417777 0 1 .
```
