### ISSUE TITLE
Element X in DensityCalculator

### ISSUE THREAD

**Issue by keitaroyam** [project-gemmi/gemmi#167]
If the model includes atoms with element X (=0), they seem to lead to unexpected behaviour in DensityCalculator, because it tries to access `Table::data[-1]`.
https://github.com/project-gemmi/gemmi/blob/009757b9d3a8c464d501b08677fcb2a86f96a66f/include/gemmi/dencalc.hpp#L104-L108
https://github.com/project-gemmi/gemmi/blob/009757b9d3a8c464d501b08677fcb2a86f96a66f/include/gemmi/it92.hpp#L35-L39

Is it programmer's responsibility to check `Table::has()` for all elements? It might be better to raise an exception or ignore such atoms in `add_atom_density_to_grid()`.

**Comment by wojdyr** [comment]
Initially the idea was that all elements are checked first:
https://github.com/project-gemmi/gemmi/blob/009757b9d3a8c464d501b08677fcb2a86f96a66f/include/gemmi/dencalc.hpp#L82
but then I forgot about it and it's not documented.

I'll changed it, but I wonder, is it better to ignore X or use coefficients of some other atom? In Global Phasing software X is treated as O.

**Comment by wojdyr** [comment]
I added a separate set of coefficients for X. They can be set with

    gemmi.Element('X').it92.set_coefs()

**Comment by keitaroyam** [comment]
Nice! Thank you.
