### ISSUE TITLE
Parsing files with lipids and other things seems to fail - workaround and fix

### ISSUE THREAD

**Issue by bHimes** [project-gemmi/gemmi#169]
I was parsing this [pdb](https://amarolab.ucsd.edu/files/covid19/PSF-PDB_spike_open_prot_glyc_memb_wat_ions_amarolab.tar.gz) that is a fully solvated spike/membrane complex using the following:

```c++
// I'm sure there is already something in GEMMI to do an iteration like this.
for (gemmi::Model& model : st.models)
{		
  for (gemmi::Chain& chain : model.chains)
  {
    for (gemmi::Residue& res : chain.residues)
    {
      // For now, we only want ATOM 
      if (res.het_flag == 'A')  // 'A' = ATOM, 'H' = HETATM, 0 = unspecified
      {
        for (gemmi::Atom& atom : res.atoms) 
        {

```

This would die because the element was unknown (el.oridinal() == 0) for lines like this:

```
ATOM  1c210 C210 POPEM 354      88.281 -11.047  -6.071  0.00  0.00      MEMB  

```

My current workaround is to try to see if the element is "recoverable" but I'm sure this is risky:
**Note** that 
```c++
my_atoms.Item(current_atom_number).name = wxString(atom.name);
```

Workaround:

```c++
// Check to see if it is unrecognized by gemmi and try to recover.
if (atom.element.ordinal() == 0)
{
  // Strip any whitespace and take the first character of the wxString
  my_atoms.Item(current_atom_number).name = my_atoms.Item(current_atom_number).name.Trim(true).Trim(false).Mid(0,1);
  // Creat a new element from that string, if it is recognized it should pass, if not, it will be 0 again and caught in the switch below.
  gemmi::Element el = gemmi::Element(my_atoms.Item(current_atom_number).name);
  atom.element = el;
}
```

**Comment by wojdyr** [comment]
I haven't come across a file like this before, but the element is unambiguous – `C210` clearly means C, so I just fixed it in gemmi.

I don't see why your example would die when the element is unknown. It shouldn't. Some PDB files have unknown elements (marked explicitly as X).

**Comment by bHimes** [comment]
> I haven't come across a file like this before, but the element is unambiguous – `C210` clearly means C, so I just fixed it in gemmi.
> 
> I don't see why your example would die when the element is unknown. It shouldn't. Some PDB files have unknown elements (marked explicitly as X).

Sorry, incomplete context. I'm just working Gemmi into my simulator and downstream I have a check that requires all ATOM records to be of known atom type. The goal is to avoid silent ommisions in the generated density maps. I should probably replace that with a counter, and only throw an error if "epsilon" percent are unknown.
