### ISSUE TITLE
Cannot read NH2 chem comp

### ISSUE THREAD

**Issue by otienoanyango** [project-gemmi/gemmi#17]
The CCDs NH2, NH, GTE, DML and TML fail to parse. 

gemmi seems to fall over on the `_pdbx_chem_comp_identifier.identifier` which has an unquoted string like `$l^{2}-azane`.

gemmi returns either "Wrong number of values in the loop" if the value is in a loop or "expected value" if in a pair.

I suspect it has to do with the unquoted string but since I am on the python side, all I get is a RunTimeError at `gemmi.cif.read(file_path)` method and nothing more.

**Comment by wojdyr** [comment]
Are these the same files as for example:
https://files.rcsb.org/ligands/view/NH2.cif ?

I see that these strings are quoted:

    NH2 "SYSTEMATIC NAME" "OpenEye OEToolkits" 1.5.0 "$l^{2}-azane"

and gemmi reads it without errors.

**Comment by otienoanyango** [comment]
I just verified that this is a problem with our internal files. Will look to sort that out internally
