### ISSUE TITLE
Redundant operators returned by generators_from_hall

### ISSUE THREAD

**Issue by biochem-fan** [project-gemmi/gemmi#173]
As shown below, `gemmi.generators_from_hall` returns more operators than necessary to generate a space group.

```python
import gemmi

sg = gemmi.find_spacegroup_by_name('C2/c')
print(sg.hall)
#'-C 2yc'

for g in gemmi.generators_from_hall(sg.hall): print(g)
#<gemmi.Op("x,y,z")>
#<gemmi.Op("-x,y,-z+1/2")>
#<gemmi.Op("-x,-y,-z")>
#<gemmi.Op("x+1/2,y+1/2,z")>
#<gemmi.Op("-x+1/2,y+1/2,-z+1/2")>
#<gemmi.Op("-x+1/2,-y+1/2,-z")>
```

Actually we need only four operators (identity, 2-fold, inversion, C-centering), not six.
See https://www.cryst.ehu.es/cryst/get_gen.html (space group 15).

**Comment by biochem-fan** [comment]
Gemmi cannot find a space group from 'generators' produced by Gemmi itself.

```python
gemmi.find_spacegroup_by_ops(gemmi.generators_from_hall(gemmi.find_spacegroup_by_name("P1").hall))
# <gemmi.SpaceGroup("P 1")> 
gemmi.find_spacegroup_by_ops(gemmi.generators_from_hall(gemmi.find_spacegroup_by_name("P2").hall))
# <gemmi.SpaceGroup("P 1 2 1")>
gemmi.find_spacegroup_by_ops(gemmi.generators_from_hall(gemmi.find_spacegroup_by_name("C2").hall))
# <gemmi.SpaceGroup("C 1 2 1")>
gemmi.find_spacegroup_by_ops(gemmi.generators_from_hall(gemmi.find_spacegroup_by_name("C2/c").hall))
# fails
```

**Comment by biochem-fan** [comment]
OK, this is not a problem; I understood `find_spacegroup_by_ops` does not close a group, so it needs full operators.

So only `gemmi.generators_from_hall` is the problem.

**Comment by wojdyr** [comment]
The result of `gemmi.generators_from_hall` is stored in GroupOps, which keeps centering operators separately, but combines them with symmetry operators when it's iterated.
To get a list of actual generators you'd need to add sym_ops and cen_ops:

```py
import gemmi

sg = gemmi.find_spacegroup_by_name('C2/c')
generators = gemmi.generators_from_hall(sg.hall)
gen_list = list(generators.sym_ops)
for cen in generators.cen_ops[1:]:  # skip [0,0,0]
    gen_list.append(gemmi.Op().translated(cen))
for g in gen_list:
    print(g)
#<gemmi.Op("x,y,z")>
#<gemmi.Op("-x,y,-z+1/2")>
#<gemmi.Op("-x,-y,-z")>
#<gemmi.Op("x+1/2,y+1/2,z")>
```

**Comment by biochem-fan** [comment]
I see. Thank you very much for explanation and document update.
