### ISSUE TITLE
Expose GroupOps::add_missing_elements() to Python

### ISSUE THREAD

**Issue by biochem-fan** [project-gemmi/gemmi#175]
I would like to use GroupOps::add_missing_elements() from Python. Could you please expose it?

The following patch seems to do the job.

```diff
diff --git a/python/sym.cpp b/python/sym.cpp
index b0ed0ff0..1af29f18 100644
--- a/python/sym.cpp
+++ b/python/sym.cpp
@@ -110,6 +110,7 @@ void add_symmetry(py::module& m) {
     .def_readwrite("sym_ops", &GroupOps::sym_ops,
                "Symmetry operations (to be combined with centering vectors).")
     .def_readwrite("cen_ops", &GroupOps::cen_ops, "Centering vectors.")
+    .def("add_missing_elements", &GroupOps::add_missing_elements)
     .def("find_centering", &GroupOps::find_centering)
     .def("has_same_centring", &GroupOps::has_same_centring)
     .def("has_same_rotations", &GroupOps::has_same_rotations)
```

Background: I would like to produce LATT and SYMM records for SHELX (as in https://cci.lbl.gov/cctbx/shelx.html). To do this, I take the list of generators, remove lattice centerings and the inversion operator if present and close the group by `add_missing_elements`.

**Comment by wojdyr** [comment]
I added it, good to know it's being used.
I haven't added python bindings and documentation for many functions because I thought no one will ever need it.

**Comment by biochem-fan** [comment]
Thank you very much!
