### ISSUE TITLE
Crash with table.erase()

### ISSUE THREAD

**Issue by dkratzert** [project-gemmi/gemmi#179]
Hi,
I encountered a crash of gemmi while erasing a table:

```
>>> doc = gemmi.cif.read_file('test-data/p21c.cif')
>>> doc.sole_block().find_loop_item('_geom_bond_atom_site_label_1').loop.width()
5
>>> table = doc.sole_block().find(['_geom_bond_atom_site_label_1',
        '_geom_bond_atom_site_label_2',
        '_geom_bond_distance',
        '_geom_bond_site_symmetry_2',
        '_geom_bond_publ_flag'])
>>> table
<gemmi.cif.Table 126 x 5>
>>> table.erase()
-> crash
```

You can find the respective CIF here: https://github.com/dkratzert/FinalCif/blob/master/test-data/p21c.cif

**Comment by wojdyr** [comment]
Unfortunately, I can't reproduce it and I don't see what's wrong there.
I modified Table::erase() to make sure that the table is not used after erase(), but it's rather unrelated to the crash.

**Comment by dkratzert** [comment]
I tested your fix and it seems to work:

[...]
```
>>> table.erase()
>>> table
<gemmi.cif.Table nil>
```

**Comment by wojdyr** [comment]
good!
