### ISSUE TITLE
python FloatGrid <-> C++ Grid<float> Conversion

### ISSUE THREAD

**Issue by ConorFWild** [project-gemmi/gemmi#18]
Curretly, python side functions like transform_f_phi_to_map return gemmi.FloatGrid, a python class rather than the underlying C++ Grid. 

This seems problematic as there doesn't seem to be a easy way to pass grids generated on the python side back to C++ for more intensive operations like resampling.

I think this could be fixed relatively easily by making the underlying C++ object accessible as a property?

**Comment by wojdyr** [comment]
Python function returns Python object that wraps C++ object.
This is how the underlying C++ object is made accessible from Python.
If you have a C++ function that takes Grid<float> as an argument, Python bindings to this function would take FloatGrid as an argument.

**Comment by ConorFWild** [comment]
So thats how I thought it worked, and indeed seems to do in most cases, but if I have a pybind function like:
```
m.def("test_grid",
		[](gemmi::Grid<float> grid)
		{
			return "Loading grid<float> worked";
		},
		"Test if grids load");
```

Then when ran in python with a FloatGrid

`module.test_grid(grid)`

Where grid is a gemmi.FloatGrid that comes from, say, mtz.transform_f_phi_to_map, it results in a type error:

```
TypeError: test_grid(): incompatible function arguments. The following argument types are supported:
    1. (arg0: gemmi::Grid<float>) -> str

Invoked with: <gemmi.FloatGrid(200, 240, 144)>
```

**Comment by wojdyr** [comment]
Perhaps it's because these functions are in a different module than Grid? I didn't look into details, but I copied the test_grid function above to python bindings in gemmi, and calling `gemmi.test_grid(grid)` worked.
