### ISSUE TITLE
Would you like to provide us slab-generator function?

### ISSUE THREAD

**Issue by zhangfq-chemistry** [project-gemmi/gemmi#189]
Thanks a lot for this very useful work!

**Comment by wojdyr** [comment]
What is slab-generator?

**Comment by zhangfq-chemistry** [comment]
![image](https://user-images.githubusercontent.com/57468494/154883597-030cd879-15d6-4860-bef5-a8bf5c245baf.png)

**Comment by zhangfq-chemistry** [comment]
just like this : https://www.golectures.com/index.php?go=search&q=VESTA%20Software%20-%20ZrO2%20%5B111%5D%20Slab%20Model%20with%20Vacuum%20tutorial

**Comment by wojdyr** [comment]
It's interesting, but I'm afraid it's outside of the scope of this project, which is focused on macromolecular crystallography.
