### ISSUE TITLE
Construct Ops from Seitz Arrays

### ISSUE THREAD

**Issue by kmdalton** [project-gemmi/gemmi#191]
Would it make sense to add a constructor to `gemmi.Op` which takes a 4x4 array of floats in the Seitz format? It might be useful if `gemmi` could support the triplet -> float_seitz -> triplet round trip. 

I'm not sure if it would introduce too many hard decisions about how to express fractional values. Curious to hear your thoughts.

**Comment by kmdalton** [comment]
Here is python function that converts `Op.float_seitz` output into triplets. Perhaps it could be useful. 

```python
import gemmi
from fractions import Fraction
import numpy as np

def seitz_to_triplet(seitz, den=24):
    seitz = np.array(seitz)
    seitz_den = np.round(seitz * den).astype(int)
    triplet = []
    for row in seitz_den[:3]:
        singlet = ""
        for factor,variable in zip(row, ['x', 'y', 'z', '']):
            if factor == 0:
                continue
            frac = Fraction(factor, den)
            if frac == 1:
                singlet += f'+{variable}'
            elif frac == -1:
                singlet += f'-{variable}'
            elif frac > 0:
                singlet += f'+{frac}{variable}'
            else:
                singlet += f'{frac}{variable}'
        triplet.append(singlet.lstrip("+"))
    return ",".join(triplet)
```

I'll note that this passes the following test,
```python
for sg in gemmi.spacegroup_table():
    for op in sg.operations():
        seitz = op.float_seitz
        triplet = seitz_to_triplet(seitz)
        assert op == gemmi.Op(triplet)
```
which implies this function might be enough to round trip all the relevant ops in gemmi. 

This was useful for me while writing a problem about Harker sections for a class. I'm not sure if there might be other uses. When thinking of `ops` as "general positions" you might sometimes want to do arithmetic on the Seitz arrays. Then it is nice to be able to get the triplet notation back.

**Comment by wojdyr** [comment]
Yes, it make sense to have such a function. I implemented it an hour ago, but then got distracted by other things.
I pushed it now: function `gemmi.seitz_to_op(seitz_matrix)`.
Hopefully works as expected.

**Comment by kmdalton** [comment]
Thanks!
