### ISSUE TITLE
Axis reordering question: test output seem to be incorrect

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [project-gemmi/gemmi#197]
Dear all,

I have a question regarding new functionality (reordering axis). But first of all, thank you very much for developing this library, and including such functionality in particular. It is really versatile tool! :+1: Also thanks to the creator of this @wojdyr for his responsiveness.

To the question:
https://github.com/project-gemmi/gemmi/blob/1aafaaf370f4217b7bdea148623d252407ceb4dc/tests/test_grid.py#L113-L116
If my understanding is correct, here the original iota_yzx.ccp4.gz file should have axis order [1, 2, 0]. However, when I download that file from the repo, read it, and checked the axis order, the output is different:
```
>>> m = gemmi.read_ccp4_map('iota_yzx.ccp4.gz', setup=False)
>>> m.axis_positions()
[2, 0, 1]
```

Maybe there is some mistake on my side, but I cannot recognize it. Do you think the test/source code is correct? I apologize in advance if I got the thing wrong.

Best regards,
Aliaksei

**Comment by aliaksei-chareshneu** [comment]
As a follow-up, I just would like to confirm if this function indeed reorders axis such that the order becomes always X, Y, Z (NC, NR, NS or NX, NY, NZ in CCP4 terminology) for any possible axis order in the input file?

**Comment by aliaksei-chareshneu** [comment]
@wojdyr, thank you very much for a prompt response. I see that you fixed the test now.
To be sure, could you confirm that this:
```
setup(float('nan'), gemmi.MapSetup.ReorderOnly) 
```
indeed reorders axis such that the order becomes always X, Y, Z (NC, NR, NS or NX, NY, NZ in CCP4 terminology) for any possible axis order in the input file?

**Comment by wojdyr** [comment]
Yes, it does.
(if it doesn't than it's a bug)

**Comment by aliaksei-chareshneu** [comment]
> Yes, it does. (if it doesn't than it's a bug)

Thanks!
However, it seems that output of this
```
 m.header_i32(17), m.header_i32(18), m.header_i32(19)
```
which is (2, 3, 1), i.e. Y, Z, X
does not much with the output of this:
```
m.axis_positions()
```
which is [2, 0, 1], i.e. Z, X, Y
(both before the setup is called)

Or I misunderstood something?

**Comment by wojdyr** [comment]
2,3,1 in the header means: first axis is Y, second Z, third X.
axis_positions() are 0-based and the meaning is 0-based positions of X axis, Y axis and Z axis.
So [2,0,1] here means: X is third (2), Y is first (0), Z is second (1).
Both have the same meaning, but it's admittedly confusing. Because of this axis_positions() was initially planned as internal-only function and is not documented.

What do you use CCP4 maps for?

**Comment by aliaksei-chareshneu** [comment]
> What do you use CCP4 maps for?

Thanks for the clarification and sorry for misunderstanding.
Mainly for visualization. If I may ask, why do you ask it? :smiley:

**Comment by wojdyr** [comment]
Just out of curiosity :-)

If it'd happen that your map is too big to fit into memory, and if you use Python, you can try [mrcfile](https://github.com/ccpem/mrcfile) instead.
