### ISSUE TITLE
JOSS review on documentation - statement of need

### ISSUE THREAD

**Issue by dominiquesydow** [project-gemmi/gemmi#203]
Hi @wojdyr,

One of the checklist items for my review is the following:

> A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

I could not find this in the documentation, yet. I recommend copying the "Statement of need" section in the paper to the documentation as a subsection under "Introduction" (after the paper has been finalized).

**Comment by dominiquesydow** [comment]
Link to the review: https://github.com/openjournals/joss-reviews/issues/4200

**Comment by wojdyr** [comment]
The audience is mentioned at the very beginning of the introduction https://gemmi.readthedocs.io/en/latest/

> primarily for use in macromolecular crystallography [...]
> Parts of this library can be useful in structural bioinformatics (for symmetry-aware analysis of protein models), and in other molecular-structure sciences that use CIF files

When reading it myself, it could be reworded and the chemical crystallography could be mentioned explicitly. But I'd rather not compare gemmi with other libraries in the documentation.

**Comment by wojdyr** [comment]
I reworded minimally the introduction.
