### ISSUE TITLE
JOSS review on documentation - community guidelines

### ISSUE THREAD

**Issue by dominiquesydow** [project-gemmi/gemmi#204]
Hi @wojdyr and @jamesrhester,

As part of my review, I'd like to follow up the discussion around the community guidelines that already started here: https://github.com/openjournals/joss-reviews/issues/4200#issuecomment-1080081599

As part of the documentation, GEMMI should have:
> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

For me, the README addition that you made [here](https://github.com/openjournals/joss-reviews/issues/4200#issuecomment-1085029015) works nicely. I think this still needs to be added also to the documentation - agreeing with @jamesrhester, a "Contributing" section would make sense (e.g. after the "Installation" section).

Link to the review: https://github.com/openjournals/joss-reviews/issues/4200

**Comment by wojdyr** [comment]
I just edited the manual (page [index.html](https://gemmi.readthedocs.io/en/latest/index.html)) to mention GitHub Issues and Discussions.
It's not worded in the same way as in the README, but please consider the README as part of the documentation (the "Contributing" section being in README is already in the documentation).
