### ISSUE TITLE
cif2mtz with multiple blocks and missing cell - 5e2b

### ISSUE THREAD

**Issue by CV-GPhL** [project-gemmi/gemmi#205]
When converting the second block with
```
gemmi cif2mtz -B 2
```
we get a MTZ file with
```
 SPACEGROUP  179
 CELL           1.000    1.000    1.000  90.000  90.000  90.000
 WAVELENGTH   1.54180
 LABELS      H K L M/ISYM BATCH I SIGI
 TYPES       H H H      Y     B J    Q
```
Obviously, it is the mmCIF file that is at fault here (no ``_cell`` category in that block), but maybe ``gemmi cif2mtz`` could try and fix that by using the cell from the first block (plus a big warning message)?

**Comment by wojdyr** [comment]
yes, that's what I was doing for space groups, so now I added the same treatment for unit cells.
