### ISSUE TITLE
SmallMolecule suggestions

### ISSUE THREAD

**Issue by biochem-fan** [project-gemmi/gemmi#211]
Using the `SmallMolecule` class to calculate structure factors, I came up with two suggestions.

1. Apparently `Site.u_iso` is ignored on structure factor calculation when `Site.aniso` is set. Is this by design? If so, it would be nice to have this documented.
2. We have to call `SmallMolecule.setup_cell_images()` before structure factor calculation. Can this be automatically called in the setter functions of `SmallMolecule.spacegroup_hm` and `SmallMolecule.cell`? Otherwise, it would be nice to document this function.

**Comment by wojdyr** [comment]
> 
>     1. Apparently `Site.u_iso` is ignored on structure factor calculation when `Site.aniso` is set. Is this by design?

Yes. Should u_iso be added to aniso?

**Comment by biochem-fan** [comment]
> Should u_iso be added to aniso?

My intuition was that both `u_iso` and `aniso` were taken into account for structure factor calculation. But I'm not sure if that is the standard treatment in other libraries/programs. @yam_cpp, what do you think?
