### ISSUE TITLE
Update to PEGTL v3

### ISSUE THREAD

**Issue by merkys** [project-gemmi/gemmi#212]
PEGTL v3 has been released. Are there any plans to update GEMMI to be compatible with PEGTL v3? In particular, is the embedded copy of PEGTL in GEMMI is going to be updated?

**Comment by wojdyr** [comment]
I'm afraid it's not planned currently, because PEGTL 3 requires C++17 and gemmi still supports older compilers.

**Comment by merkys** [comment]
Thanks for prompt answer.

**Comment by joelb123** [comment]
I'd like to request this decision be reconsidered. From the downstream packaging point of view, many distros strongly discourage using bundled third-party libraries, and PEGTL 2 is going away. PEGTL 3.2.6 fixed a bug in demangle under gcc 12, and one would like to avoid finding out if such bugs affect CIF parsing.

Support of older compilers seems like a non-issue. Nobody should be using GCC 7 at this point, and the performance improvements seen in GCC 12 are relevant to everybody.

**Comment by merkys** [comment]
Just an observation: Debian-provided gemmi is built with pegtl 3.2.7 and it seems to work fine, its reverse dependencies seem to work fine as well.
