### ISSUE TITLE
Segmentation fault in the 'flood_fill_above' function

### ISSUE THREAD

**Issue by crisfbazz** [project-gemmi/gemmi#218]
Hello, thanks for the awesome package! It is of great help for my project :)

I am using the 'flood_fill_above' function to search for blobs in specific locations of the Fo-Fc map.
While testing my code with PDB entries I encountered a segmentation fault when calling this functions for the PDB entry [5M8G](https://www.rcsb.org/structure/5m8g).

To reproduce the error:
1. Refine this PDB entry with Dimple removing hetero atoms (obtain .mtz file with the Fo-Fc map)
2. Use gemmi to read the entry mtz file, extract the difference map, normalize the map and apply the 'flood_fill_above' function with cutoff=2 and location equals [15.4375, 20.748, -14.31]. Illustrated in the following code:
```
mtz = gemmi.read_mtz_file("5M8G.mtz")
grid = mtz.transform_f_phi_to_map('DELFWT', 'PHDELWT', sample_rate=5)
grid.normalize()
blob_mask = gemmi.flood_fill_above(grid, [gemmi.Position(15.4375, 20.748,-14.31)], threshold=2)  ## segfault
blob_volume = blob_mask.sum() * grid.unit_cell.volume / grid.point_count
```
I can provide the refined mtz file if requested.
Thanks!

**Comment by wojdyr** [comment]
Thanks for reporting it. I just fixed it.

**Comment by crisfbazz** [comment]
Great, thank you!

**Comment by crisfbazz** [comment]
Hi @wojdyr,
Would it be possible to make the 'flood_fill_above' and the 'find_blobs_by_flood_fill' functions return que position x,y,z of the points of the blobs or simple the maximum and minimum x,y,z limit values of the points? With this information it would be possible to know better the region in which the blob is located and its extent.

My goal here is to derive the dimensions of a bounding box that includes the blob without including so much adjacent noise, and for that this box should have the dimensions equals the limits of the blob in the real space.

The current problem that I'm facing is that these two functions only return the center and the volume of the blob, and it's not possible to know the location of the blob in x,y,z limits directly.

Thanks!!

**Comment by wojdyr** [comment]
flood_fill_above() returns a mask, and there is a function to find the extent of non-zero area in the mask. Only Python bindings were missing. So I just added it and the documentation. See the example with `mask.get_nonzero_extent()` in:
https://gemmi.readthedocs.io/en/latest/grid.html#flood-fill

Does it solve the problem?
(If it'd help to store the bounding box also in the Blob object – why not, I can add it in the future)

**Comment by crisfbazz** [comment]
I think it will certainly help, I'll give it a try next week and let you know.
Thank you!

**Comment by crisfbazz** [comment]
Hi @wojdyr, I finally could test the function to find the extent of non-zero area in the mask. 

What I end up noticing is that it is returning a box that is smaller than the blob image. And what I really want is the smallest box that contains the entire blob image, which is the box that contains all the non-zero values.

I attached as example the blob imagem of ligand 69F_A_1404 from PDB entry 5i8b, which is located in the position xyz 32.2145, 12.6095, 14.7855. I added two waters in the positions of the extend minimum and maximum to ilustrate.

Is there another function that gives the extent of a bounding box that contains the entire blob image?
![Screenshot at 2022-09-16 10-39-32](https://user-images.githubusercontent.com/6875229/190658826-aff644b6-3005-4e72-b8b8-bb15ccdb3a2a.png)

**Comment by crisfbazz** [comment]
A workaround that I could do is to retrieve the position of all non-zero points in the blob mask, but I think it would be a slow solution.

**Comment by wojdyr** [comment]
If you'd calculate yourself the non-zero extent of the mask and it was different than what's returned by mask.get_nonzero_extent(), then it'd be clear that the problem is in get_nonzero_extent().

**Comment by crisfbazz** [comment]
Sure!

I did it and found a small deviation of around 0.5 A.  For what I'm using, I need a good precision here to prevent loosing any part of the blob. Can you check to see if the problem is in my code or in the function? Maybe this difference could be due to the gridding spacing or something like that.

The code I used:

```
mtz = gemmi.read_mtz_file("5i8b.mtz")
grid = mtz.transform_f_phi_to_map('DELFWT', 'PHDELWT', sample_rate=5)
grid.normalize()
blob_mask = gemmi.flood_fill_above(grid, [gemmi.Position(28.5454, 13.721, 13.8142)], threshold=3)
extent = blob_mask.get_nonzero_extent()
bb_min = grid.unit_cell.orthogonalize(extent.minimum)   # [24.8287, 9.23784, 11.8807]
bb_max = grid.unit_cell.orthogonalize(extent.maximum)   # [34.262, 16.2041, 17.7477]
blob_points_index = np.where(blob_mask.array > 0)
blob_positions = np.asarray([blob_mask.get_position(blob_points_index[0][i], blob_points_index[1][i],
                                                                blob_points_index[2][i]).tolist() for i in
                                         range(len(blob_points_index[0]))])
bb_min_points = gemmi.Position(blob_positions[:,0].min(),blob_positions[:,1].min(),
                               blob_positions[:,2].min())  # [24.7501489975748, 9.38928, 12.027368802529356]
bb_max_points = gemmi.Position(blob_positions[:,0].max(),blob_positions[:,1].max(),
                               blob_positions[:,2].max())  # [34.80529173966833, 16.05264, 17.60102751589662]
bb_min_diff = bb_min - bb_min_points   # [0.0785978, -0.15144, -0.146675]
bb_max_diff = bb_max - bb_max_points   # [-0.543247, 0.15144, 0.146675]
```

I could send you the mtz file if requested.
Thanks!

**Comment by wojdyr** [comment]
The difference in y and z is half of the grid spacing. get_nonzero_extent() adds it: if grid point z=4 is 1 and z=5 is 0, the extent is assumed to be 4.5.

The bigger difference in x is because the unit cell is oblique and extent is returned in fractional coordinates. 

```
(0,1)
  v
  ________
  \        \
   \        \
    \________\
     ^
   (0,0)
```
You get different Cartesian x if you orthogonalize (0,0) and (0,1). So you can't assume that if you orthogonalize fractional (x_min, y_min, z_min) you'll get Cartesian (x_min, y_min, z_min).

You could orthogonalize all 8 corners and calculate cuboid in Cartesian coordinates that contains the cuboid in grid coordinates. But then you'd get area larger than necessary.

**Comment by crisfbazz** [comment]
Thanks for the explanation! I'll test to use the extent again with this considerations.
