### ISSUE TITLE
Access `gemmi.FloatGrid` locations as array

### ISSUE THREAD

**Issue by dennisbrookner** [project-gemmi/gemmi#222]
Hey `gemmi` team,

I've been working with some weird warpings/mappings of `gemmi.FloatGrid()` grid locations, and I'm wondering if it is / could be possible to access grid locations as an array, akin to how grid values are handled. e.g., `gemmi` can nicely do:
```python
map_values = my_map.grid.array
```
which runs ~instantly. But to achieve the equivalent with map locations, I've been doing something like:
```python
grid_size = (256,256,256)
map_locs = []
for a in range(grid_size[0]):
    for b in range(grid_size[1]):
        for c in range(grid_size[2]):
            map_locs.append(my_map.grid.get_position(a,b,c).tolist())      
```
which takes ~minutes for a large grid.

If this functionality already exists, and I'm just missing it, great! If not, would this be easy/possible to implement?

**Comment by wojdyr** [comment]
Perhaps doing it in NumPy would be faster. `grid.get_position(a,b,c)` gives the same result as multiplying 3x3 matrix `grid.unit_cell.orth.mat` by vector [a/grid_size[0], b/grid_size[1], c/grid_size[2]].  So one could create first an array with all (a,b,c), then divide it by grid_size and multiply it by the 3x3 matrix.
But why do you need such a list of locations? What do you do with it next?

**Comment by wojdyr** [comment]
Out of curiosity: do you want to align maps without models?
