### ISSUE TITLE
prepare_topology does not change serial numbers on atoms

### ISSUE THREAD

**Issue by gyromagnet** [project-gemmi/gemmi#223]
Hello! I have enjoyed working with gemmi but I have run into a problem.

I want to use prepare_topology to generate all the bonds in a biological assembly. I am using the following code to do so:
```
s = [
    gemmi.make_structure_from_block(block)
    for block in gemmi.cif.read('./1OUT.cif')
][0]

res_names = list({
    e_1
    for e_0 in s
    for e_1 in e_0.get_all_residue_names()
})
mon_lib = gemmi.read_monomer_lib('./ccp4-8.0/lib/data/monomers', res_names)

print(len([cra.atom.serial for cra in st[0].all()])) # number of atoms
print(len({cra.atom.serial for cra in st[0].all()})) # number of distinct serials
s.transform_to_assembly('1', gemmi.HowToNameCopiedChain.AddNumber)
print(len({cra.atom.serial for cra in st[0].all()})) # number of atoms has doubled
print(len({cra.atom.serial for cra in st[0].all()})) # number of distinct serials stayed the same

t = gemmi.prepare_topology(
    s,
    mon_lib,
    model_index=0,
    # h_change=gemmi.HydrogenChange.ReAdd,
    reorder=False,
    warnings=sys.stderr,
    ignore_unknown_links=False,
)
```

As far as I know, if I want to relate the bonds in t.bonds back to the residue and chain they come from, I either have to compare gemmi.Atom objects or use their serials. Using their serials does not work after transform_to_assembly because the serials for the atoms in the new chains are identical to the old ones. The only thing distinguishing the Atom objects from their symmetry-related counterparts is their position.

One option is to add an offset to the serials in the duplicated atoms.

Another option, that I think would be more in keeping with the principle of separating topology and geometry, would be to have topology restraints refer to AtomAddresses instead of referring to Atoms directly.

Is there some way to accomplish what I want that I have missed?

Thanks,
Joseph

**Comment by gyromagnet** [comment]
That seems to only be one of my problems. If I renumber the atom serials after transform_to_assembly (or make_assembly) all of the peptide bonds and other connections have been removed. Is it possible to create a structure representing the full assembly while retaining all peptide bonds and other connections?

Thanks,
Joseph

**Comment by wojdyr** [comment]
Hi Joseph
perhaps Topo class is not appropriate here. Or perhaps it would be appropriate if it had python bindings to more functions from C++. I don't know.
What do you want to do with the bonds?

As for atom serials and peptide bonds – could you elaborate? What does it mean that connections have been removed?

**Comment by gyromagnet** [comment]
Essentially, I want to be able to read an mmcif, build the biological assembly, and have access to a graph of the chemical structure. Currently, if I follow the example in the documentation under graph analysis to make a networkx graph from the structure, it works appropriately before running make_assembly or transform_to_assembly, but fails after either function.

I believe this is because the chain ids are being changed on the original copy of the molecules and new chain IDs are being assigned to the copies but the connections stored at structure.connections do not have the chain id updated. Below is an example using 1OUT, a structure only containing one copy each of alpha and beta hemoglobin.

Here is a complete script to generate the following graphs:
```

import sys
import gemmi
import matplotlib.pyplot as plt
import networkx as nx

s = [
    gemmi.make_structure_from_block(block)
    for block in gemmi.cif.read('./1OUT.cif')
][0]

res_names = list({
    e_1
    for e_0 in s
    for e_1 in e_0.get_all_residue_names()
})
mon_lib = gemmi.read_monomer_lib('./ccp4-8.0/lib/data/monomers', res_names)

# s.transform_to_assembly('1', gemmi.HowToNameCopiedChain.AddNumber)

t = gemmi.prepare_topology(
    s,
    mon_lib,
    model_index=0,
    # h_change=gemmi.HydrogenChange.ReAdd,
    reorder=False,
    warnings=sys.stderr,
    ignore_unknown_links=False,
)

pos = {}
for cra in s[0].all():
    pos[cra.atom] = (cra.atom.pos.y, cra.atom.pos.z)

g = nx.Graph()
for bond in t.bonds:
    g.add_edge(id(bond.atoms[0]), id(bond.atoms[1]))

# silly renaming of nodes because the nodes are converted to strings when sent to graphviz
d = {str(a):a for a in g.nodes()}
pos = nx.nx_pydot.graphviz_layout(g, prog='neato')
pos = {d[n]:p for n,p in pos.items()}

fig, ax = plt.subplots(1,1, figsize=(10,10), dpi=100)
nx.draw_networkx_edges(
    g,
    pos=pos,
    ax=ax,
    width=0.5,
)
ax.set_aspect(1.0)
```

Here is the graph generated by that code:
![image](https://user-images.githubusercontent.com/109091463/184444803-328e33d0-8d3c-4db1-a8b9-79804bbfbcf3.png)

Here is the graph generated from the 1OUT if the transform_to_assembly line is uncommented: 
![image](https://user-images.githubusercontent.com/109091463/184444934-9a2676d6-6906-4567-afe4-4686931c2b0c.png)

I get a similar result if I replace the transform_to_assembly line with:
`s[0] = gemmi.make_assembly(s.assemblies[0], s[0], gemmi.HowToNameCopiedChain.AddNumber)`

Thanks for your time.

**Comment by wojdyr** [comment]
Nice graphs.
I started looking into it, but I came across more problems. I should be able to sort it out later this week.

**Comment by wojdyr** [comment]
I improved `transform_to_assembly()`. Now it re-assigns serial numbers and adds connections.
Except intramolecular connections (links other than 1_555) – this would require more work.
I didn't test it much. If you'd come across cases that don't work correctly, let me know.

`id()` doesn't work reliably in my hands, it's better to use serial numbers. I modified you script to generate the graph below:

```py
import os
import sys
import gemmi
import matplotlib.pyplot as plt
import networkx as nx

s = gemmi.read_structure('./1OUT.cif')
mon_lib = gemmi.read_monomer_lib(os.environ['CLIBD_MON'],
                                 s[0].get_all_residue_names())
s.transform_to_assembly('1', gemmi.HowToNameCopiedChain.AddNumber)

t = gemmi.prepare_topology(
    s,
    mon_lib,
    model_index=0,
    # h_change=gemmi.HydrogenChange.ReAdd,
    reorder=False,
    warnings=sys.stderr,
    ignore_unknown_links=False,
)

g = nx.Graph()
for bond in t.bonds:
    g.add_edge(bond.atoms[0].serial, bond.atoms[1].serial)
pos = nx.nx_pydot.graphviz_layout(g, prog='neato')

fig, ax = plt.subplots(1,1, figsize=(10,10), dpi=100)
nx.draw_networkx_edges(
    g,
    pos=pos,
    ax=ax,
    width=0.5,
)
ax.set_aspect(1.0)
ax.margins(0.0)
plt.axis("off")
plt.show()
```

![1eof-assembly-graph](https://user-images.githubusercontent.com/491873/186673663-5ac9ec88-9524-4ecf-bc7f-03de77cf2a3a.png)
