### ISSUE TITLE
Command line application unavailable from PyPI

### ISSUE THREAD

**Issue by kmdalton** [project-gemmi/gemmi#224]
Whenever I `pip install gemmi`, the `gemmi` program does not end up in my path. Actually, I'm not even certain the binary ends up on my disk at all. I don't have this problem with the `conda` package. Is this a limitation of `setuptools`? Can this be resolved by adding some `entry_points` or `package_data` flags to `setup()`? Thanks!

**Comment by wojdyr** [comment]
I was also thinking about builiding the gemmi program in setup.py, but from what I could see, setuptools don't support it.
Alternatively, the wheels could be built using CMake. But on the other hand, the program doesn't really belong to Python wheels – it has nothing to do with Python. And it's simpler to build wheels with setuptools.

**Comment by kmdalton** [comment]
I install `gemmi` most often using `pip`. Usually it ends up in my environment when I install `reciprocalspaceship` or `careless`. I prefer to do it this way, so I can make sure I'm using a version that satisfies the `rs` `setup.py`. Unfortunately, this means I rarely have the command line program available. Which is a shame, because it is useful! 

I think what you're telling me is that it is either impossible or undesirable to distribute the program with wheels? I certainly understand if this is the case. I was just not sure if this is a big ask or not. Anyway, let me know what you think. I can of course install the program with `conda` as needed.

**Comment by wojdyr** [comment]
I'm not against having the program in python wheels, but it'd probably require significant work and much more complex setup than we have now (now all the wheels are built by [this github action][1]), so I don't have plans to work on it.

As an alternative, you can also download binaries from CI (although they might be less portable)
https://gemmi.readthedocs.io/en/latest/install.html#binaries

[1]: https://github.com/project-gemmi/gemmi/blob/master/.github/workflows/wheels2.yml

**Comment by eggplants** [comment]
How about including the CLI binary as `package_data`, writing a Python script to wrap it and set to `entry_points`?

**Comment by wojdyr** [comment]
@eggplants first you need to compile that binary

**Comment by kmdalton** [comment]
nice work! thanks!
