### ISSUE TITLE
tests/test_hkl.py fails on multiple architectures

### ISSUE THREAD

**Issue by merkys** [project-gemmi/gemmi#225]
`tests/test_hkl.py` possibly has tolerance too low to pass on arm64, i386 and some other architectures. Build matrix [here](https://buildd.debian.org/status/package.php?p=gemmi).

**Comment by wojdyr** [comment]
Thanks for reporting it. Hopefully it's fixed now.

**Comment by merkys** [comment]
On top of your changes I had to change `4e-2` to `6e-2` in the following line to have tests passing on arm64:
https://github.com/project-gemmi/gemmi/blob/68709e905520cf4273607d8f61f5a98cc7cea076/tests/test_hkl.py#L26

**Comment by wojdyr** [comment]
Good to know, it's now set to 6e-2.

**Comment by merkys** [comment]
I can confirm that with these 3 linked commits tests now pass on all architectures supported by Debian.
