### ISSUE TITLE
Gaps in make_one_letter_sequence

### ISSUE THREAD

**Issue by awaterho** [project-gemmi/gemmi#233]
Hello,
I have some admittedly odd structures, the one in question is https://modelarchive.org/doi/10.5452/ma-bak-cepc-0527.cif

If I read the structure, find chain B, get the polymer I see 421 residues. 
structure[0].find_chain('B').get_polymer()
<gemmi.ResidueSpan of 421: B [1(MET) 2(SER) 3(GLN) ... 421(THR)]>

However, if I call make_one_letter_sequence() on that polymer, I get a 424 character string, with some gaps. 
'MSQLTEFISCIPVVNEEQNEEDERGLCKIQIEDGAMLETLDENSLSGLRIEKMLVSEGTGIFSKSSFGINDLRIFTGENIDEESKKYVWYELLKMLTGHKVHIASLDEKVVFTKWTCRMQDDEVWKVVMELESSAIIRKIAELTLHPVKKGEIDLFEMADKLYKDICCVNDSYRNIKESDSSNRNRVEQLARERELLDRLLETRDERTRAMMVTLLNEKKKKIRELHEILRQNNIKLSDDDVLDSALINTEVQKPISELNSPGKRMKRRKTVVEPQNLQKKLKDTSRRRANRKISNQSVLKMEDDDFDDFQFFGLSKRPIITANDKLSEKDDDITSFGDDTQSISFESDSSSDVQKHLVSLEDNGIQISAGRSDEDYGDISGSESETDASAGEKK-SSNHSEQSGNDREP-CSQTESETDIE-T'

There are some odd bonds between those residues, but is there a reason the gaps are inserted? 

A different approach, 
''.join([gemmi.find_tabulated_residue(x.name).one_letter_code for x in structure[0].find_chain('B')]) would result in 
'MSQLTEFISCIPVVNEEQNEEDERGLCKIQIEDGAMLETLDENSLSGLRIEKMLVSEGTGIFSKSSFGINDLRIFTGENIDEESKKYVWYELLKMLTGHKVHIASLDEKVVFTKWTCRMQDDEVWKVVMELESSAIIRKIAELTLHPVKKGEIDLFEMADKLYKDICCVNDSYRNIKESDSSNRNRVEQLARERELLDRLLETRDERTRAMMVTLLNEKKKKIRELHEILRQNNIKLSDDDVLDSALINTEVQKPISELNSPGKRMKRRKTVVEPQNLQKKLKDTSRRRANRKISNQSVLKMEDDDFDDFQFFGLSKRPIITANDKLSEKDDDITSFGDDTQSISFESDSSSDVQKHLVSLEDNGIQISAGRSDEDYGDISGSESETDASAGEKKSSNHSEQSGNDREPCSQTESETDIET'

**Comment by wojdyr** [comment]
In this function gaps are assumed when the distance between residues (between CA atoms) is >5A.
Gemmi has a couple different methods for checking if residues are connected. This one is the simplest one.
These three "gaps" in this chain correspond to distances 5.08, 5.27, 5.13.
