### ISSUE TITLE
CCP4 maps: grid size is not compatible with space group

### ISSUE THREAD

**Issue by crisfbazz** [project-gemmi/gemmi#236]
Hi,

 I'm having a problem when reading CCP4 maps created by PanDDA, the chosen grid_size causes the following error: "RuntimeError: grid size is not compatible with space group".
  When opening the same maps in Coot, the symmetry operations work fine. 
   
 I can't pass you a CCP4 map as example write now, but below is the map attributes that gave this error:

-  shape = (270, 625, 300)
- unit_cell = (134.801, 300.725, 144.641, 90, 112.74, 90)
- spacing = (0.46045444554488546, 0.48116001599999997, 0.4446594676815208)
- spacegroup = "P 1 21 1"

 Looking at the API docs it seemed to me that the "set_size_from_spacing" function could help to correctly set a grid size. Can you make it available for the python package? 

Thanks

**Comment by wojdyr** [comment]
The reason this error is that the y size is odd, while the space group has symmetry operator -x,y+1/2,-z. Normally the map grid has the same symmetry as the crystal. If it doesn't, some functions that use symmetry don't work. The next version of PanDDA is to change how the map size is chosen.

You can't just change the grid size without changing the data. But you could change the space group to P1. What function triggers the exception?

**Comment by crisfbazz** [comment]
Thanks for the explanation!

The function that triggers the exception is the symmetrize_max() indeed. And when I tried to skip the use of this function, the values that I extracted from this map with the "wrong" size seemed to be misaligned with the real data. When I do the same with a map without this exception everything works fine.

I need a solution to be applied to a generic case that works for all space groups, so manually changing it would not be very robust.

**Comment by crisfbazz** [comment]
I realized that the space group P1 could work for all cases, but still I'm facing this misalignment problem. It seems that the map is displaced by a rotation.

**Comment by CV-GPhL** [comment]
Dear all,

remember that a map might not be an actual crystallographic object and
you can't use anything to do with symmetry (including cell
repeaets!). The Clipper library would have the distinction between
Xmap and NXmap to help keeping these separate, in gemmi you have to
keep track of that distinction yourself. E.g. an event map in from
PanDDA is the result of masking and transformation ... resulting in a
non-crystallographic object. You need to first push the density onto a
truly crystallographic grid (via interpolation and optional
transformation) before you can start playing with symmetry.

This is all fairly obvious if you think about non-crystallograhphic
(or cross-crystal) averaging in the context of density modification
(so really "old stuff"), but equally relevant for multi-dataset/xtal
map analysis ... at least that's how I handle it when using gemmi/C++
;-)

Cheers

Clemens

On Fri, Oct 21, 2022 at 11:14:21AM -0700, crisfbazz wrote:
> I realized that the space group P1 could work for all cases, but still I'm facing this misalignment problem. It seems that the map is displaced by a rotation. 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/project-gemmi/gemmi/issues/236#issuecomment-1287289772
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>

-- 

*--------------------------------------------------------------
* Clemens Vonrhein, Ph.D.     vonrhein AT GlobalPhasing DOT com
* Global Phasing Ltd., Sheraton House, Castle Park 
* Cambridge CB3 0AX, UK                   www.globalphasing.com
*--------------------------------------------------------------

**Comment by wojdyr** [comment]
I understand that this is fixed in PanDDA - in code that's in development, there were no releases of PanDDA for long time.
 
Why do you want to apply symmetry operations to this map?

**Comment by crisfbazz** [comment]
I was using this maps to clone and create new maps in which I need to apply symmetry operations. It is just for completeness in all symmetric mates, for allowing visualizing the new maps from any symmetric mate. Now I am using a map created with gemmi from a mtz file instead and is all good!
