### ISSUE TITLE
[Question] Read/Write model chain from mmCIF to mmCIF or PDB format.

### ISSUE THREAD

**Issue by tinchogb** [project-gemmi/gemmi#24]
Hi @wojdyr , 
First of all, thanks for this awesome tool !
Since two days ago I was reading the documentation and doing some testing in RCSB mmCIF files.
And when a was trying to get a particular model chain a few doubts came to me.

At the moment I did this to get all models:
```
doc = gemmi.cif.read_file('2mfe.cif')
block = doc.sole_block()
```
#### 1 WAY  
```
models = block.find('_atom_site.', ['group_PDB', 'id', 'type_symbol', 'label_atom_id', 'label_alt_id', 'label_comp_id', 'label_asym_id', 'label_entity_id', 'label_seq_id', 'pdbx_PDB_ins_code', 'Cartn_x', 'Cartn_y', 'Cartn_z', 'occupancy', 'B_iso_or_equiv', 'pdbx_formal_charge', 'auth_seq_id', 'auth_comp_id', 'auth_asym_id', 'auth_atom_id', 'pdbx_PDB_model_num'])

models
Out: <gemmi.cif.Table 65280 x 21>
```
#### 2 WAY
```
models = block.find_mmcif_category('_atom_site.')

models
Out: <gemmi.cif.Table 65280 x 21>
```
#### 3 WAY
```
models = block.find_loop('_atom_site.group_PDB').get_loop()

models
<gemmi.cif.Loop 65280 x 21>
```
Now I got a problem...
**How I could save in mmCIF or PDB (style PDBx) format those models from chain "D" in separate files?**

I'm stack with this poorly solution:
```
for row in models:
   if row[6] is 'D':
       print('%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s ' % tuple(row))
```
On the other hand, I was trying Biopython (v1.76) PDB class, which they get above result doing this:
```
from Bio.PDB import MMCIFParser() as p
from Bio.PDB import MMCIFIO() as io

file_path = "2mfe.cif"
pdb_code = file_path.split('.')[0]
chain = "D"
file = open(file_path, "r")
structure_file = p.get_structure(pdb_code, file)
for model in structure_file:
    filename = (pdb_code + "_" + str(model.id) + "_" + chain + ".cif")
    io.set_structure(model[chain])
    io.save(filename)
```
Biopython's results only have this loop data (missing **'_atom_site.pdbx_formal_charge '**, **'_atom_site.auth_comp_id'** and **'_atom_site.auth_atom_id'**):
```
data_pdb
#
loop_
_atom_site.group_PDB
_atom_site.id
_atom_site.type_symbol
_atom_site.label_atom_id
_atom_site.label_alt_id
_atom_site.label_comp_id
_atom_site.label_asym_id
_atom_site.label_entity_id
_atom_site.label_seq_id
_atom_site.pdbx_PDB_ins_code
_atom_site.Cartn_x
_atom_site.Cartn_y
_atom_site.Cartn_z
_atom_site.occupancy
_atom_site.B_iso_or_equiv
_atom_site.auth_seq_id
_atom_site.auth_asym_id
_atom_site.pdbx_PDB_model_num
ATOM ....
...
HETATM ....
#
```

**Comment by wojdyr** [comment]
Hello,

I don't understand what you want on the output.
> those models from chain "D" in separate files

you meant atoms? Chains A, B, C and D are part of the same model.

**Comment by tinchogb** [comment]
Hi !
Yes, atoms, sorry for my bad explanation.
Like in this RCSB entry: [2mfe.cif](https://www.rcsb.org/structure/2MFE). Has 20 models. I want to extract '_atom_site.' from each chain on each model. I took one example, chain 'D'.
The thing is that I need to save them in same mmcif format or PDB format.

**Comment by wojdyr** [comment]
Do you want to save 20 models in one file, but each model with only one chain?
What about other data from the mmCIF file (tables other than _atom_site)?

**Comment by tinchogb** [comment]
Other data than '_atom_site.' would be great to have also, for sure ! I have not asked for those because I thought that could be too much. Moreover, I was trying *gemmi* program also and I saw that you already incorporate sequence alignment tools. So, I was also wondering if you have thought to incorporate structural alignment tools to it? That's the main reason of why I need to separate, extract and save in a new file these chains from several models.

**Comment by wojdyr** [comment]
structure alignment - no, I don't plan it

writing models with one chain only - you can do it as you started, on the cif syntax level. Alternatively, you could create gemmi.Structure, leave only the chain that you want and save it in either PDB or mmCIF format.

```
import gemmi
  
st = gemmi.read_structure('2mfe.cif')
# deletes chains other than D
for model in st:
    for chain in model:
        if chain.name != 'D':
            del chain[:]
st.write_minimal_pdb('output.pdb')
```

**Comment by tinchogb** [comment]
Thanks, that could be one way. But I think there should be a more efficient solution to allow for extraction of several chains to independent files. Do you think there could be an easy way to do it?

**Comment by wojdyr** [comment]
You can use functions `add_model()` and `add_chain()` to construct Structure objects with only selected models and chains. Then you can write each Structure to a file.

**Comment by tinchogb** [comment]
Thanks @wojdyr !! that is great for my purpose.
