### ISSUE TITLE
gemmi cif2mtz and wavelength issue?

### ISSUE THREAD

**Issue by CV-GPhL** [project-gemmi/gemmi#242]
Running

```
wget wget https://files.rcsb.org/download/4E0E-sf.cif.gz
gemmi cif2mtz -B 1 4E0E-sf.cif.gz block1.mtz
```

results in the MTZ file having
```
 * Dataset ID, project/crystal/dataset names, cell dimensions, wavelength:

        1 unknown
          unknown
          unknown
             35.8800  146.4700   72.3700   90.0000   99.7100   90.0000
             0.00000
```
So somehow the wavelength got lost ... although it is in the mmCIF file:
```
...
loop_
_diffrn_radiation_wavelength.id 
_diffrn_radiation_wavelength.wavelength 
1 0.97903 
2 0.91837 
...
loop_
_refln.crystal_id
_refln.wavelength_id
_refln.scale_group_code
_refln.index_h
_refln.index_k
_refln.index_l
_refln.status
_refln.F_meas_au
_refln.F_meas_sigma_au
_refln.F_calc
_refln.phase_calc
1 1 1  -12    0    2 o     93.3    4.5      175.8     0.0 
...
```
This is using
```
gemmi --version
gemmi 0.5.7 (v0.5.7-127-g4ce6d2c)
```

**Comment by wojdyr** [comment]
mmCIF file has two wavelengths, not one. Picking one of multiple wavelengths as "the wavelength" didn't seem right.

**Comment by CV-GPhL** [comment]
But the _refln loop has a pointer (_refln.wavelength_id) to the correct one:

https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_refln.wavelength_id.html

So there should not be any confusion about picking the correct one here ... right?

**Comment by wojdyr** [comment]
The PDB software prefixes merged reflections with `1 1 1 ` that formally corresponds to
```
_refln.crystal_id
_refln.wavelength_id
_refln.scale_group_code
```
It's 1 1 1 for all reflections in all entries, so it's a signature of the software rather than information about the data.
Obviously, having crystal ID and wavelength ID assigned to *merged* reflection doesn't make much sense, and I don't even know what was the idea behind scale_group_code.
In short, I'd rather not rely upon it.

**Comment by CV-GPhL** [comment]
Not all reflections (_refln loop) contain a fixed "1 1 1" in all entries ... at least not if you look beyond data block 1. E.g. 4E0E has 
_refln.wavelength_id set to 2 in block 3. It is described as
```
data_r4e0esf
# 
loop_
_audit.revision_id 
_audit.creation_date 
_audit.update_record 
1_0 2012-05-02 
;The data loops contain the following:
 structure factors used in refinement, from crystal 173170 that is a Met-Inhibition crystal. 
 unmerged original index intensities of data set used for refinement and phasing, this data set comes from crystal 173170 that is a Met-Inhibition crystal, wavelength 1.
 unmerged original index intensities of data set used for phasing, this data set comes from crystal 173170 that is a Met-Inhibition crystal, wavelength 2.
 experimental phases from crystal 173170 that is a Met-Inhibition crystal.
 density modified experimental phases from crystal 173170 that is a Met-Inhibition crystal.
;
```

Ok, not very machine readable ... but if one would go back all the way to the original JCSG archive (yes, I kept a copy of the  beautifully annotated JCSG database), it is clear that the data was refined against the 0.97903 A wavelength - exactly as given (block 1 has a wavelength_id of 1 that points to the right value). I would think that in nearly all cases where multiple wavelengths are given, the pointer in the _refln loop is actually correct ... at least that seems a better assumption than just ignoring those values and setting the MTZ wavelength item(s) to 0.0 ;-)

It becomes tricky for blocks N>1 if they don't contain a _diffrn_radiation_wavelength blocks ... but that is more to do with bugs in deposited mmCIF reflection data. At least for block 1 it would do the right thing here I think.

**Comment by wojdyr** [comment]
Wavelength 0.0 in MTZ means unknown. So it's not set to incorrect value. It's left as unknown.

If someone puts two wavelength into a block with merged data, I'm hesitant to assume that only one is relevant to the data in this block, because I don't know if it's always (or almost always) a valid assumption.

**Comment by CV-GPhL** [comment]
Hi Marcin,

On Tue, Nov 29, 2022 at 05:06:42AM -0800, Marcin Wojdyr wrote:
> I see that 3hsa and other entries deposited by JCSG have this layout with all wavelengths in the first block. JCSG likely used custom software to prepare deposition files, so that's consistent.

Yes (JCSG was way ahead of most others at the time - both in
annotation and deposition).

> If I take other entries (not from JCSG), it's not that clear. 7koa has wavelengths:
> 
>     1 1.02
>     2 1.18

Yes - and _refln.wavelength_id is 1, so ...
 
> but in the coordinate file I see *… by Pink-Beam Serial Crystallography* and
> 
>     _diffrn_source.pdbx_wavelength_list        1.02-1.18
> 
> Perhaps the average (1.10?) would be more appropriate here.

... I would definitely use 1.02 here. It is not up to a file
conversion to start interpret the correctness of a value. We have to
assume that a user giving us

 r7koasf:[_diffrn_radiation_wavelength.id] 1
 r7koasf:[_diffrn_radiation_wavelength.wavelength] 1.02
 r7koasf:[_diffrn_radiation_wavelength.id] 2
 r7koasf:[_diffrn_radiation_wavelength.wavelength] 1.18
 r7koasf:[_refln.wavelength_id] 1

knew what they were doing. Otherwise we should consider all those with
values of 1.0000 and 1.5418 as being suspicious ;-)
 
> Note that referencing crystal_id and wavelength_id from each
> individual **merged** reflection has little sense, because if all
> reflections are from the same crystal and wavelength, then it's not
> needed,

Ture.

> and if the data was merged from different crystals and
> wavelengths, assigning one crystal and wavelength to each reflection
> is not sufficient.

But it might not be merged from different crystals and wavelengths:
you could have multiple datasets inside a single _refln loop similar
to multiple F/SIGF columns in a MTZ file (think: F_native and
F_derivative etc). So I think that crystal_id/wavelength_id business
makes sense - even if we don't use it often now or tend to put things
into differnet data blocks.

Cheers

Clemens

**Comment by wojdyr** [comment]
> ... I would definitely use 1.02 here. It is not up to a file
> conversion to start interpret the correctness of a value. We have to
> assume that a user giving us
> 
>  r7koasf:[_diffrn_radiation_wavelength.id] 1
>  r7koasf:[_diffrn_radiation_wavelength.wavelength] 1.02
>  r7koasf:[_diffrn_radiation_wavelength.id] 2
>  r7koasf:[_diffrn_radiation_wavelength.wavelength] 1.18
>  r7koasf:[_refln.wavelength_id] 1
> 
> knew what they were doing.


Yes, they specified range 1.02-1.18 in the only possible way in this file.
Don't pay too much attention to `_refln.wavelength_id`. It's added automatically, possibly on the PDB side of the deposition, so it's usually not meaningful.

> But it might not be merged from different crystals and wavelengths:
> you could have multiple datasets inside a single _refln loop similar

It wouldn't work: (h,k,l) is the index of this table, so it must be unique.

**Comment by wojdyr** [comment]
I added warning for 2+ wavelengths, and an option to set the wavelength from the command line.

 I suppose that JCSG people were putting all the wavelengths into the first block because of software constraints (it could be either the software they used for mmCIF preparation or the software that the PDB used for deposition processing).
A good practice (with reasonable software) would be that a block with data contains only the wavelengths that were used to collect the data in this block. This would be also consistent with how the unit cell parameters are stored.
