### ISSUE TITLE
incorrect assembly formed by gemmi compared to RCSB

### ISSUE THREAD

**Issue by danny305** [project-gemmi/gemmi#244]
I was doing some quality assessment and found that gemmi makes mistakes in forming the biological assembly. Not sure if this is due to an error in the RCSB cif file or a gemmi bug. I will explain my findings below.

For PDB ID 7n7w:
- protein is a homo-hexamer
- biological assembly forms a trigonal prism (3 promoters interact with 3 other protomers along a single face)
- RCSB file has a dimer not in the correct orientation.
- gemmi correctly forms 1 of the 3 protomer assemblies and incorrectly forms the second 3 protomer assembly
- RCSB enables one to download the biological assembled structure but you lose a lot of the metadata in the cif file (like the x-ray resolution and biological assembly metadata)

RCSB cif:
![image](https://user-images.githubusercontent.com/31376682/206887672-66083b60-3418-4874-9223-28fb1dcd4ce4.png)

gemmi cif assembly:
![image](https://user-images.githubusercontent.com/31376682/206887681-6a762836-d600-4b8b-a0c7-8c0695c0f2b2.png)

RCSB assembly cif:
![image](https://user-images.githubusercontent.com/31376682/206887691-46ffdad4-5453-4de7-96a9-0d97ca972d09.png)

Here is my gemmi code to produce the biological assembly (copied from the gemmi docs):
```python 
def _build_assembly(self):

        # "1" or "unit_cell"
        # self.structure.transform_to_assembly(
        #     "1", 
        #     gemmi.HowToNameCopiedChain.Short
        # )

        assembled_model = gemmi.make_assembly(
            self.structure.assemblies[0], 
            self.structure[0], 
            gemmi.HowToNameCopiedChain.Short
        )

        del self.structure[0]

        self.structure.add_model(assembled_model)
```
Both ```make_assembly() and transform to assembly()``` with "1" or "unit_cell" arguments give the wrong assembly structure.

Really hope this bug can be figured out so large datasets of biological assembled structures with all their corresponding metadata can be confidently curated. 

Danny

**Comment by wojdyr** [comment]
Sorry for not replying when you reported it.
I tried to reproduce it now, but I got an assembly that looks like your last image:
![gemmi-7n7w-assembly1](https://user-images.githubusercontent.com/491873/236949599-ec0b58fc-c501-4716-8bef-d2e82e500e12.png)

I used this for testing:
```py
st = gemmi.read_structure(path)
st.transform_to_assembly("1", gemmi.HowToNameCopiedChain.Short)
st.write_pdb('out.pdb')
# or
#st.make_mmcif_document().write_file('out.cif')
```
Perhaps I changed something relevant in gemmi in the meantime – I don't really remember.
If you (or anyone else) would still see this problem, please re-open it.
