### ISSUE TITLE
Pip install doesn't work

### ISSUE THREAD

**Issue by drorhunvural** [project-gemmi/gemmi#246]
`!pip install git+https://github.com/project-gemmi/gemmi.git`

Normally I was using the pip install command above and it was working. Currently pip install is not working due to a change made in the last 5-10 hours

I am getting an error like below

`ImportError: /usr/local/lib/python3.8/site-packages/gemmi.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK5gemmi3Mtz13write_to_fileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

**Comment by drorhunvural** [comment]
`!conda install -c conda-forge gemmi ` is working right now but `pip` installation still is not working

**Comment by wojdyr** [comment]
It should be fixed now.

**Comment by drorhunvural** [comment]
Same problem happened after released new version

**Comment by wojdyr** [comment]
What's the error? I don't see anything wrong.
