### ISSUE TITLE
Update cif.Style.Pdbx to write aligned columns and formatted pairs values 

### ISSUE THREAD

**Issue by roshkjr** [project-gemmi/gemmi#247]
I am in the process of moving from pdbecif package to gemmi for handling mmcif files. I found gemmi really useful to manipulate mmcf file. Thanks to all developers. However, while writing mmcif files in mmcif/Pdbx format (cif.Style.Pdbx) using gemmi, the output file is not well formatted as the one produced by pdbecif. Especially in the case of loop in mmcif, it would be nice if the columns are aligned. For pairs if all the values in a particular category are starting from the same distance (say 8 space from the longest key in the category), then it would be nice. 
[1tqh_bio.cif.gz](https://github.com/project-gemmi/gemmi/files/10383862/1tqh_bio.cif.gz)

**Comment by wojdyr** [comment]
Yes, it'd make sense for Style.Pdbx to be more similar to the files from the PDB.
Would it work if the alignment was the same as with cif.Style.Aligned?

**Comment by roshkjr** [comment]
More or less. But cif.Style.Aligned can be improved. Since cif.Style.Aligned keeps a constant number of spaces between key-value pairs, in some cases with longer key names the output does not look clean. 

For loops,the columns can be made right aligned instead of left aligned. I have attached two output files written using pdbecif and gemmi (cif.Style.Aligned) for your reference
[pdbecif_gemmi_outputs.zip](https://github.com/project-gemmi/gemmi/files/10426429/pdbecif_gemmi_outputs.zip)

**Comment by wojdyr** [comment]
Is the right alignment one of the options in pdbecif, or the default style?
The official mmCIF files from the PDB have left-aligned columns. Right-aligned columns with text don't look good.

**Comment by cypreeti** [comment]
We have Style::Pdbx  and Style::Aligned separately but I think the issue here is we want to use them together so that Style::Pdbx style can be left-aligned following the official mmCIF file format. Can we do this already? if not, please can we have this option added. Thanks.
