### ISSUE TITLE
Segmentation fault in a ContactSearch setup

### ISSUE THREAD

**Issue by lpravda** [project-gemmi/gemmi#25]
Hi guys, thanks for this tool. I've encountered segmentation faults for a couple of entries with the latest version (as of writing this post) of gemmi from the master branch and I wonder if anyone could have a look what is wrong. I'm using it from python.

## Setup 
OS: MacOS: 10.15.4
python: 3.7.7

## minimal code to reproduce the issue
```python
import gemmi
path = '1to4-assembly-1_atom_site.cif.gz '
st = gemmi.read_structure(path)
st.setup_entities()
st.remove_ligands_and_waters()

cs = gemmi.ContactSearch(distance)
cs gemmi.ContactSearch.Ignore.SameChain
sub_cells = gemmi.SubCells(st[0], st.cell, 6)
sub_cells.populate() # here it blows up
```

It crashes for the assembly id 1 for all of the following structures:  

1to4, 2gpc, 4xvv, 2hk3, 3n77, 3fbt, 3chi, 3esf, 2r3v, 4yiw, 2x4i, 5hm4, 3kbf, 4f2n, 3mux, 4whj
3zrd, 3glv, 3mnd, 4u04, 2goj, 1e59, 1tz3, 3clk, 2pmr, 3toe, 1y7y, 2xhf, 2wcu, 3p9x

You can download the assembly file from here: http://www.ebi.ac.uk/pdbe/static/entry/download/1to4-assembly-1_atom_site.cif.gz

**Comment by wojdyr** [comment]
Hi Lukas,
I'm trying to reproduce it. There are some copy&paste mistakes in the code you included.
In particular in line:
```
cs gemmi.ContactSearch.Ignore.SameChain
```
I just deleted this line, but I didn't manage to reproduce the problem.
Could you copy the code again?

**Comment by wojdyr** [comment]
@lpravda do you still have the code to reproduce the problem?

**Comment by lpravda** [comment]
Hi Marcin, sorry I was offline for the past two days. the line you are pointing at should read:

```
cs.ignore = gemmi.ContactSearch.Ignore.SameChain
```

I've rerun the code and I've realised I confused consoles. The target platform is not macOS (that one works). But I'm experiencing issues in Linux:

OS: Red Hat 7.4
Kernel: Linux 3.10.0-693.5.2.el7.x86_64

I know these cross-platform issues are sometimes very difficult to track, so I wonder if there is anything else I could provide you with to locate the root cause of the issue.

full code:
```
import gemmi

path = '1to4-assembly-1_atom_site.cif.gz'
st = gemmi.read_structure(path)
st.setup_entities()
st.remove_ligands_and_waters()

cs = gemmi.ContactSearch(5.0)
cs.ignore = gemmi.ContactSearch.Ignore.SameChain
sub_cells = gemmi.SubCells(st[0], st.cell, 6)
print('it works up to here')
sub_cells.populate()  # and then blows up
print("so it never gets here")
```

**Comment by wojdyr** [comment]
Was it also python 3.7 on Red Hat?

**Comment by lpravda** [comment]
yes the exact same version 3.7.7

**Comment by wojdyr** [comment]
I didn't manage to reproduce it, but here are things that you could try.

I did a small change to gemmi.SubCells(). I don't know if it's relevant to this issue, but you could try to update gemmi (uninstall and install - to be sure it's updated) and see if it still crashes.

Next, you could try replacing

    sub_cells = gemmi.SubCells(st[0], st.cell, 6)

with:

    sub_cells = gemmi.SubCells(st, 6)
although it is unlikely to help. I just added the second form in the latest commit.

You could remove lines:

    cs = gemmi.ContactSearch(5.0)
    cs.ignore = gemmi.ContactSearch.Ignore.SameChain

and see if anything changes.

And also lines:

    st.setup_entities()
    st.remove_ligands_and_waters()

You could also try running it under valgrind:

    PYTHONMALLOC=malloc valgrind python3.7 script.py

but there are plenty false positives.

But first try updating gemmi.

**Comment by lpravda** [comment]
So I updated gemmi, changed the constructor and removed the lines you suggested, but that did not help. I hope to have a bit more time to play around with valgrind in the afternoon and will let you know if I can get anything reasonable out of that. Thank you for your help.

**Comment by wojdyr** [comment]
Do you happen to use Anaconda Python?
If you do, you can install gemmi (just released ver. 0.3.7) using conda.
In the meantime I renamed `SubCells` to `NeighborSearch`, so you'd need to change it.

**Comment by wojdyr** [comment]
Hi, hopefully this problem is gone (or not relevant anymore)?
I'll close this issue now. If you still get any segfaults, please reopen.

**Comment by lpravda** [comment]
Hi @wojdyr I resolved the issue by running the process at different machine with different OS and did not have any problem since. I'm just about to run some more analysis, so I'd provide you with some meaningful logs if anything occurs. Thanks a lot for your help!
