### ISSUE TITLE
cif Block, erase certain columns

### ISSUE THREAD

**Issue by richardjgowers** [project-gemmi/gemmi#251]
I'm trying to slim down the Chemical Component Dictionary cif, a bit like in the documentation.  Erasing entire items works fine, but I can't seem to erase columns from a table.  E.g if I do `block.find_loop_item('_chem_comp_bond.pdbx_ordinal').erase()` the entire loop is erased.

Is this as intended (i.e. tables can't be partially erased)?  Is a better way to do this instead to create a new Document with new Blocks and only copy across the data I want to keep?

Thanks

**Comment by wojdyr** [comment]
There are indeed no functions to add or remove columns. I'll think about adding them.

If you use python, you could use get_mmcif_category(), delete unwanted dict items, and then set_mmcif_category().

**Comment by wojdyr** [comment]
This week, I added functions `Loop.add_columns()` and `Loop.remove_column()`.
Now I added also `Column.erase()`:

    block.find_values('_chem_comp_bond.pdbx_ordinal').erase()
