### ISSUE TITLE
Example for parsing a cif file from RCSB to a protein file and a ligand file

### ISSUE THREAD

**Issue by KSUN63** [project-gemmi/gemmi#253]
Hi there, 

I recently started to jump into the field of computational biology and thus have this really naive request for a simple example of how to parse a cif file into a protein file and a ligand file of any format (preferably with bond order info for the ligand).

So far, I explored the entity class of gemmi and believe that what I need now is to output each polymer and non-polymer entity into a separate file. Is there any easy way of doing that? If you wouldn't mind, can you leave an example code block? I would really appreciate your help!

Best,
Oliver

**Comment by KSUN63** [comment]
I am trying to generate separate protein and ligand files for molecular
docking. Don’t know if separating entities is the right thing to do but I
kind of want to output files that separate protein information from the
ligand.

**Comment by CV-GPhL** [comment]
Just out of interest: are you thinking along the line of PDBQT files
for ligand and "receptor" as used e.g. in AutoDock programs - but cast
into CIF format?

**Comment by KSUN63** [comment]
More or less. I think Autodock already has there pipelines so maybe some
other software like glide. Also, I had the impression that cif file
contains more info than pdb so that I don’t have to suffer from missing
atoms. Is this correct? If not I think I’m fine with just sticking to pdb

**Comment by wojdyr** [comment]
mmCIF files may have more metadata, but for sure the atoms are not missing in PDB files.

If you want to get only a part of the model (a protein or a ligand), you can remove unwanted chains and residues from the original structure and save the result to a file (in particular, method remove_ligands_and_waters() leaves only polymers). Or you can copy selected chains to a new model and save it to a file.
But I suppose there are other, more established ways of preparing input files for each docking software.
