### ISSUE TITLE
The possible transformation matrices forms connecting a pair of enantiomorphic space groups in a given dimension.

### ISSUE THREAD

**Issue by hongyi-zhao** [project-gemmi/gemmi#254]
Suppose S1 and S2 are a pair of enantiomorphic space groups, I wonder what are the possible transformation matrices forms connecting them, such that C1^-1 * S1 * C1 = S2, in a given dimension, say, 4.

Any tips will be appreciated.

Regards,
Zhao

**Comment by wojdyr** [comment]
Hi Zhao,
it seems you won't get an answer here.
Since it's rather a mathematical question, I'm inclined to close it.
