### ISSUE TITLE
Since v0.6.0 cannot "import gemmi"

### ISSUE THREAD

**Issue by neumannrf** [project-gemmi/gemmi#259]
I had been using `gemmi==0.5.8` until recently, but when I inadvertently upgraded to the latest version, I lost the ability to import the Python library.

## Steps to reproduce
1. Create a fresh environment with `conda create -y -n gemmi gemmi=0.6.0`
2. Activate the environment with `conda activate gemmi`
3. Open a Python terminal with `python`
4. Try to import the library and get this error

    ```Python
    >>> import gemmi
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'gemmi'
    ```

### Note

Downgrading to `v0.5.8` fixes it, but several packages (e.g. [pyGAPS](https://github.com/pauliacomi/pyGAPS/blob/master/setup.cfg#L55)) that depend on `gemmi` will install the latest version.

**Comment by wojdyr** [comment]
I just tried it and it works for me.
You need to investigate it on your computer. Is gemmi module (gemmi.*.so or *.pyd) present in that new environment?

**Comment by neumannrf** [comment]
Thank you for looking into this issue!

No, there is no `gemmi.*.so` nor any `*.pyd` file inside `/opt/homebrew/Caskroom/miniconda/base/envs/gemmi/`. 

I am using `conda 23.1.0` with `Python 3.11.0` on macOS 13.2.1 (Ventura). 

This is the same computer that can successfully `import gemmi` when I install `gemmi=0.5.8` instead of `gemmi=0.6.0`.

**Comment by wojdyr** [comment]
Well, if gemmi can be imported, it must be somewhere.

**Comment by neumannrf** [comment]
But `gemmi=0.6.0` cannot be imported. That is what I'm trying to explain...

Gemmi v0.6.0 cannot be imported and there are no `gemmi.*.so` nor `*.pyd` files in the environment.

This bug was probably introduced by v0.6.0 because until v0.5.8 this was not happening.

**Comment by neumannrf** [comment]
No, when I install `gemmi-0.5.8` I get a `gemmi.cpython-311-darwin.so` file, but when I install `gemmi-0.6.0` I get nothing of the sort.

I installed `gemmi` from conda-forge using the commands listed [above](https://github.com/project-gemmi/gemmi/issues/259#issue-1629971990).

This is the resulting environment:
```Shell
$> conda list
# packages in environment at /opt/homebrew/Caskroom/miniconda/base/envs/gemmi:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.12.7            h4653dfc_0    conda-forge
gemmi                     0.6.0           py311h7b25133_0    conda-forge
libcxx                    15.0.7               h75e25f2_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.40.0               h76d750c_0    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
openssl                   3.1.0                h03a7124_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
python                    3.11.0          h3ba56d0_1_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
setuptools                67.6.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
```
or, if you prefer,
```Shell
conda env export
name: gemmi
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2022.12.7=h4653dfc_0
  - gemmi=0.6.0=py311h7b25133_0
  - libcxx=15.0.7=h75e25f2_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.40.0=h76d750c_0
  - libzlib=1.2.13=h03a7124_4
  - ncurses=6.3=h07bb92c_1
  - openssl=3.1.0=h03a7124_0
  - pip=23.0.1=pyhd8ed1ab_0
  - python=3.11.0=h3ba56d0_1_cpython
  - python_abi=3.11=3_cp311
  - readline=8.1.2=h46ed386_0
  - setuptools=67.6.0=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tzdata=2022g=h191b570_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/gemmi
```

**Comment by neumannrf** [comment]
@wojdyr This seems to have been fixed in YVR feedstock repo. I'm away from my computer these days, but I'll test and report later.
