### ISSUE TITLE
Fails to build with GCC 13

### ISSUE THREAD

**Issue by merkys** [project-gemmi/gemmi#268]
It has been reported that gemmi fails to build with GCC 13. Full report is here: https://bugs.debian.org/1037671. The report lists gemmi version 0.5.7, but the same issue occurs in 0.6.2 as well. Currently this is not a serious issue, but the next Debian release in 2025 is planned to bump GCC to version 13.

**Comment by wojdyr** [comment]
It was fixed in #264, but possibly I introduced other compilation problems since then, because I'm not testing with GCC 13 yet. I'm using Ubuntu 22.04 now. I'll start using GCC 13 when I find it packaged for Ubuntu 22.04, or when I upgrade the system. It will be for sure before 2025.

**Comment by wojdyr** [comment]
Fixed now. I used gcc 13 inside docker and added `#include <cstdint>` where it was missing.

**Comment by merkys** [comment]
Great, thanks!

**Comment by merkys** [comment]
I can confirm that 9c668e726c4b8fb57330a15b53d630351808fcfa fixes the issue with GCC 13.
