### ISSUE TITLE
Linking issue using conda-forge package of gemmi on linux

### ISSUE THREAD

**Issue by agrossfield** [project-gemmi/gemmi#275]
Hi,

I've run into an issue trying to use the package of gemmi distributed via conda-forge. Basically, everything works beautifully on OSX, but on linux I get an error when linking against a c++ library I maintain:
`lto1: fatal error: bytecode stream in file '/home/alan/miniconda3/envs/loos/lib/libgemmi_cpp.a' generated with LTO version -25390.6 instead of the expected 8.1
compilation terminated.`

From what I've read, this issue usually occurs when the toolchains used are incompatible. Since I was building with the conda -forge toolchain, this suggests an issue with the building of the gemmi package (though of course it's possible I'm making an error). 

I opened an issue about this on the gemmi-feedstock, but it's been a week and no one responded there. I'm cross-posting it here in hopes of catching a developer's attention. 

The relevant issue is:
https://github.com/conda-forge/gemmi-feedstock/issues/57

Thanks,

Alan

**Comment by wojdyr** [comment]
You could try building `libgemmi_cpp.a` from source.

**Comment by agrossfield** [comment]
Unfortunately, other than testing (which you’re right, I need to do to nail down the problem 100%), that’s a non-starter for me. My package is distributed via conda-forge, which means I need to pull my dependencies from conda-forge — that’s how they build our binaries to distribute them.

Message ID: ***@***.***>

Has anyone else run into this problem? It seems like it should happen to anyone trying using the libgemmi_cpp on Linux.

**Comment by wojdyr** [comment]
gemmi-feedstock has not been updated for 6 months and it currently doesn't build on Macos. I'll try to update it myself soon.
