### ISSUE TITLE
Enhancement: Extend Python API to Support --nfree Argument Functionality

### ISSUE THREAD

**Issue by vivek8031** [project-gemmi/gemmi#278]
**Description**: 
Currently, the Gemmi command-line tool offers the `--nfree` argument, which provides essential functionality for certain operations. However, this specific feature is missing from the Gemmi Python API.

**Context**:
During our development process, we had to directly invoke the `gemmi mtz2cif` via the subprocess module to leverage the `--nfree` argument, bypassing the Python Gemmi package. Integrating this feature into the Python API would streamline our workflows and likely benefit other users with similar requirements.

**Suggestion**:
Please consider adding support for the `--nfree` argument or its equivalent functionality directly within the Gemmi Python API. This enhancement will allow for a more seamless and pythonic approach to tasks requiring this feature.

**Comment by wojdyr** [comment]
OK, I added MtzToCif::free_flag_value to python bindings.
