### ISSUE TITLE
[Feature Request] Python Acess to UnmergedHklMover

### ISSUE THREAD

**Issue by kmdalton** [project-gemmi/gemmi#28]
Right now there is no obvious way to map an unmerged miller index to the reciprocal space asymmetric unit from Python. At the C++ level, the closest thing seems to be the UnmergedHklMover in mtz.hpp. It would be really great if we could have access to this object through Pybind11. @JBGreisman and I have reimplemented this functionality with numpy, but we would like to be able to compare it to Gemmi's implementation for testing purposes. 

More generally, might it make sense to refactor UnmergedHklMover into symm.hpp and make its constructor take a SpaceGroup instead of an Mtz. This would require a bit more work, but I think it makes sense to have a less specialized class for this task.

On an unrelated note, thanks for your work on this project. It has drastically reduced the overhead involved in processing crystallographic data in my research.

**Comment by wojdyr** [comment]
I was just looking into unmerged data in the last days.
Do you read it from MTZ or a different file format?

**Comment by kmdalton** [comment]
Regrettably, we are juggling a lot of formats at the moment. I typically read in unmerged hkl or h5 files at  and use Gemmi to write merged MTZs. It would be nice to be able to easily translate the input files which come from a variety of esoteric sources to unmerged MTZs with proper ISYM columns. 

Maybe this sort of functionality is already available, and I just missed it. At any rate, it would be good to have a function that simply takes a space group and miller index and returns the miller index inside the ASU along with the corresponding ISYM. It seemed like this was more or less available at the C++ level already. 

Let me know what you think. Thanks!

**Comment by wojdyr** [comment]
I was thinking what's the best API for such functionality.
I could, for example, add a function Mtz::set_isym() that would assume that H, K, L are actual indices (like in probably all other formats) and this function would change H K L to their asu equivalents and set ISYM.

**Comment by kmdalton** [comment]
Your suggestion would get me all the functionality I am after. Structurally, I think it still makes sense for mtz::set_isym() to call out to a function in symmetry.hpp which could also be made accessible from python. I'm thinking there could be a use case for mapping HKLs to the ASU outside of the MTZ context.

**Comment by wojdyr** [comment]
I added two functions:

    Mtz.switch_to_asu_hkl()
    Mtz.switch_to_real_hkl()

The first should do what you need. I'll document it later on.

The M/ISYM column can be at any position, but note that some programs may expect that the first 5 columns of a multi-record MTZ file are H,K,L,M/ISYM and Batch number.

**Comment by kmdalton** [comment]
That sounds great, Marcin. I'll go ahead and close this issue. Thanks!
