### ISSUE TITLE
Issue creating gemmi selections

### ISSUE THREAD

**Issue by FilomenoSanchez** [project-gemmi/gemmi#289]
Hi @wojdyr , thanks for the package, I find it really useful. I've recently noticed an issue while creating selections in structures where chains have been named with a "-" symbol. This tends to happen in CIF files for biological assemblies (for example entry [7BQX](https://www.rcsb.org/structure/7BQX), link to biological assembly file [here](https://files.rcsb.org/download/7BQX-assembly1.cif.gz)). So for instance, creating a selection as follows:
```python
import gemmi
sele = gemmi.Selection('//e-2/19(LEU)')
```
Throws the error:
```python
----> 1 sele = gemmi.Selection('//e-2/19(LEU)')

RuntimeError: Invalid selection syntax in a list near "-2/19(LE": //e-2/19(LEU)
```
For context, this is using gemmi version 0.6.2. I am not sure whether such chain names are allowed in the CIF format specifications, and since I've only seen this in files for biological assemblies I would understand if you don't consider this an issue and don't want to fix it. Otherwise it would be useful for us to have this working in gemmi. Thanks in advance!

**Comment by pschmidtke** [comment]
Not sure I can also comment on that, I have the error also on numberical chains. 
I.e. 7egb chain 8 I'm doing a selection like : '8/*/*' which yields still a runtime error

`RuntimeError: Invalid selection syntax in a list near "/*": 8/*/*`

**Comment by wojdyr** [comment]
Here it's the error message that is not clear. `8/*/*` is parsed as residue `8` atoms `*/*`. Then, processing `*/*` as a list triggers the error.

The selection syntax allows omitting leading and trailing fields. It guesses what was omitted from the first value. For numeric chain name you need to have the leading slashes:

    //8
