### ISSUE TITLE
ConnectionType.None is not accessible from python

### ISSUE THREAD

**Issue by sizmailov** [project-gemmi/gemmi#29]
`ConnectionType.None` cannot be used from python since `None` is a keyword.

Example: 
```python
import gemmi

print(gemmi.ConnectionType.Covale)
print(gemmi.ConnectionType.Disulf)
print(gemmi.ConnectionType.Hydrog)
print(gemmi.ConnectionType.MetalC)
print(gemmi.ConnectionType(4))
# print(gemmi.ConnectionType.None)
```

Syntax error (uncomment last line):
```
    print(gemmi.ConnectionType.None)
                                  ^
SyntaxError: invalid syntax
```

Current work-around: `ConnectionType.None` can be constructed as `ConnectionType(4)`

**Comment by wojdyr** [comment]
I changed it to Unknown.
Thanks for spotting it!

**Comment by sizmailov** [comment]
Cool, "Unknown" type also makes more sense than "None" type.
