### ISSUE TITLE
auto completion for gemmi grep

### ISSUE THREAD

**Issue by frmupe** [project-gemmi/gemmi#295]
For `gemmi grep` it would be super nice to have automatic completion for the tags... (something like bash autocompletion)

I have to look at the mmcif dictionary every time I use `gemmi grep` 

:P

**Comment by wojdyr** [comment]
I'd be nice, but I'm afraid I don't see any (reasonably simple) way to implement it.

You can use glob patterns if it helps:

    gemmi grep -t _*factor* 5cvz.cif
