### ISSUE TITLE
Segfault when importing `gemmi.cif`

### ISSUE THREAD

**Issue by j-c-c** [project-gemmi/gemmi#297]
Dear devs, 

After this latest release I'm running into a segfault using the python gemmi module. This is occurring in github's macOS-11 image environment with python 3.8. 

I've set up a stripped down workflow to isolate the error. After successfully installing via `pip install gemmi` I get a [segfault](https://github.com/j-c-c/TestWorkflow/actions/runs/7979549969/job/21787195262#step:4:3) on `import gemmi.cif`. 

I should note that macOS-11 is the only environment where this is occurring. 

Thanks for any help with this. 

Best,
Josh

**Comment by wojdyr** [comment]
Thanks for letting us know.
I just uploaded new wheels for macOS x86_64.
Previously, I built them on macOS 13 and they didn't work on macOS 11. No idea why. They were expected to work on 10.9 and later. Now I built them on macOS 12 and they seem to work on all Github runners.

(a note to myself: [how to update wheels in PyPI](https://stackoverflow.com/a/63944201/))
