### ISSUE TITLE
Small molecule: no _atom_site_occupancy leads to uninitialized occupancy

### ISSUE THREAD

**Issue by DmitriyMarin** [project-gemmi/gemmi#3]
**File:** `smcif.hpp`
**Function:** `make_atomic_structure_from_block`

In the case, when there is no occupancy pair defined in the cif file, it leads to the `occ` member of the `AtomicStructure::Site` being _undefined_ / _uninitialized_. Maybe, for the sake of the high-level access, it would be better to set it to `NAN` by default? For now, I am checking if the file has `_atom_site_occupancy`.

**Example:**
loop_
_atom_site_label
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
H   1.0   1.0   1.0

**Comment by wojdyr** [comment]
Thanks! I've initialized it to 1 -- I think unspecified occupancy is normally assumed to be 1. If 1 is not good, let me know.

**Comment by DmitriyMarin** [comment]
Thanks!
