### ISSUE TITLE
Question: How to make a deep copy of gemmi.Structure in python

### ISSUE THREAD

**Issue by paulsbond** [project-gemmi/gemmi#31]
Hi,

Is there a way to make a copy of a gemmi.Structure object in python? I want to write a function that takes a structure as input, makes a copy (so the original is not affected), makes some modifications (e.g. adding residues) and returns the modified structure.

I've tried `copy.copy` and `copy.deepcopy` but both give me the error:
`TypeError: can't pickle gemmi.Structure objects`

Any help would be appreciated.

Cheers,
Paul

**Comment by paulsbond** [comment]
I just found some information from another project that had the same error from a pybind11 object:
https://github.com/deepmind/open_spiel/issues/88

They point to the following in the pybind11 docs:
https://pybind11.readthedocs.io/en/stable/advanced/classes.html#pickling-support

I guess this could be quite an undertaking for a complex class though. Hopefully there'll be something simpler I'm missing. In the meantime I might just write the structure to disk and read it again.

**Comment by wojdyr** [comment]
To have deepcopy working it would be probably sufficient to implement `__deepcopy__` method. I was thinking about it, but in the end I added methods clone() to Structure, Model, Chain, Residue and Atom. It's a one-line function. I'm on the fence what's better: copy.deepcopy(st) or st.clone().

**Comment by paulsbond** [comment]
Awesome, thanks. I think either approach is fine, unless you also wanted to implement a shallow copy but I can't think of a use case for that.
