### ISSUE TITLE
Add support for BinaryCIF

### ISSUE THREAD

**Issue by jasondbiggs** [project-gemmi/gemmi#335]
According to [this page](https://www.rcsb.org/news/65a1af31c76ca3abcc925d0c) BinaryCIF is the preferred binary format for CIF data.  

The format is described in detail [here](https://github.com/molstar/BinaryCIF/tree/master).

It would be a useful new feature if gemmi could read and write BinaryCIF files.

**Comment by wojdyr** [comment]
At first, each PDB site (RCSB, PDBe and PDBj) had its own WebGL molecular viewer and its own format for passing models to the viewer:
* RCSB – NGL – MMTF
* PDBe – LiteMol – BinaryCIF
* PDBj – Molmil – mmJSON

Later, RCSB and PDBe began collaborating on the Mol* viewer, and eventually, both adopted PDBe's format, which actually borrowed a lot from MMTF.

I don't plan to support BinaryCIF. I haven't heard of any org (in academia or pharma), other than the PDB, that cares about this format. mmJSON also isn't widely used, but it was simple to add, so I gave it a try. BinaryCIF is quite complex and would take too much time to implement and maintain.

That said, I'm always interested in hearing about the uses and advantages of different formats.

On a related note, I'll add a simple binary format for CIF data for internal use: for communication between threads and for serialization. It's discussed in #258 and will hopefully require only a few lines of code.
