### ISSUE TITLE
Crash when reading an mmjson file created by gemmi

### ISSUE THREAD

**Issue by jasondbiggs** [project-gemmi/gemmi#336]
Found this when trying to test round-tripping through different formats.  Not sure if 1AB9 is special, but it was the first file I tried.

```
>>> import gemmi
>>> from gemmi import cif
>>> structure = gemmi.read_structure("/Users/jasonb/1AB9.cif")
>>> json_str = structure.make_mmcif_document().as_json(mmjson=True)
>>> with open("/Users/jasonb/1AB9_test.json", 'w') as file:
...     file.write(json_str)
... 
188699
>>> doc2 = cif.read_mmjson("/Users/jasonb/1AB9_test.json")
zsh: segmentation fault  python
```

Here is the original file (remove the .txt extension): [1AB9.cif.txt](https://github.com/user-attachments/files/17035619/1AB9.cif.txt)

The problem is that the output JSON file has an empty loop:
```
  "reflns_shell": {
   "pdbx_ordinal": [],
   "pdbx_diffrn_id": [],
   "d_res_high": [],
   "d_res_low": [],
   "percent_possible_all": [],
   "pdbx_redundancy": [],
   "Rmerge_I_obs": [],
   "pdbx_Rsym_value": [],
   "meanI_over_sigI_obs": []
  }
```
I imagine that points to a bug in the JSON writing function, but I can't speak to that.  For me the issue is the function `fill_document_from_sajson` does not check whether the arrays have zero length, and so tries to access a loop that was never created.  

I was able to fix the issue locally by putting

```
if(cif_rows < 1)
  continue;
```
right before [this line](https://github.com/project-gemmi/gemmi/blob/master/src/json.cpp#L85).

**Comment by wojdyr** [comment]
Thanks for investigating the problem. Yes, it was exactly what you wrote. Fixed now.
I also need to fix writing needless empty loops.
