### ISSUE TITLE
Publish v0.3.7 on PyPI

### ISSUE THREAD

**Issue by JBGreisman** [project-gemmi/gemmi#34]
Hi Marcin,

Thanks for the recent updates -- they have made our testing much easier. Would it be possible to push the most recent version to PyPI? I've seen it is on `conda`, but I was hoping to make sure that `pip` can reach it as well. 

I also know that you just pushed a new release very recently, but please let me know if you are planning on pushing a v0.3.8 soon with the updates to `gemmi.SpaceGroup`. 

Thanks again,
Jack

**Comment by wojdyr** [comment]
Hi Jack,

I forgot about PyPI. I published it now.

Yes, I can make v0.3.8 soon -- let say next week.

**Comment by wojdyr** [comment]
I just uploaded v0.3.8 to PyPI.
