### ISSUE TITLE
 Issue with find_nearest_pbc_position in Gemmi Neighbor Search

### ISSUE THREAD

**Issue by MichalGucwa** [project-gemmi/gemmi#340]
Dear Gemmi team,

I am reaching out to clarify whether I may be using the Gemmi library incorrectly, or if there is a potential issue with how image positions are calculated.

I am currently using Gemmi to search for neighboring atoms in the structure with PDB ID: **2fna**. My objective is to find neighboring atoms, then calculate vectors and distances relative to a reference atom. Here’s a summary of the issue I encountered:

**Problem Description**

The reference atom I’m using is in Chain A, Residue 571, Atom O. I expect the following distances to neighbors within a 3.5 Å cutoff:

    A/ASN 51/O - 2.50 Å
    A/HOH 644/O - 2.74 Å
    B/ASP 306/OD1 - expected to be ~2.8 Å (confirmed in PyMOL)

However, when using the following code to retrieve the position of B/ASP 306/OD1, I am getting an unexpectedly large distance of 66.49 Å:

```
import gemmi
CUTOFF = 3.5
st=gemmi.read_structure('2fna.pdb')
ref_atom=st[0].sole_residue('A', gemmi.SeqId('571')).sole_atom('O')
ns = gemmi.NeighborSearch(st[0], st.cell, 3.5).populate(include_h=False)
for mark in ns.find_neighbors(ref_atom, min_dist=0.1, max_dist=CUTOFF):
    if mark.image_idx == 0:
        vector = ref_atom.pos-mark.pos
    else:
        vector = ref_atom.pos - st.cell.find_nearest_pbc_position(ref_atom.pos, mark.pos, mark.image_idx)
    print(f"{mark.to_cra(st[0])}, {mark.image_idx}, {vector.length():.2f}")
```
output:
```
A/ASN 51/O,    0,   2.50
B/ASP 306/OD1, 1,  66.49
A/HOH 644/O,   0,   2.74
```

Using PyMOL, I confirmed that the expected distance between A/571/O and B/306/OD1 should be approximately 2.8 Å. Here are the PyMOL commands I used to verify this:
```
fetch 2fna
orient c. A and resid 571
symexp symmate_, 2fna, all, 3.5
show sticks
distance dist1, resid 571 and c. A and m. 2fna, m. symmate_01000100 and resid 306 and c. B and name OD1
set_view (\
    -0.556676388,    0.829529107,   -0.044606980,\
    -0.765941143,   -0.533312559,   -0.359041423,\
    -0.321623385,   -0.165703729,    0.932255507,\
     0.000000000,    0.000000000,  -20.547313690,\
     8.185000420,   70.982002258,   51.498001099,\
     5.613289833,   35.481319427,  -20.000000000 )
```

**Suggestion for Improvement**

Would it be possible to add attributes to the mark object, such as:

    vector: The vector between ref_atom.pos and mark.pos, accounting for periodic boundary conditions (PBC) if necessary.
    img_pos: image position of atom 

This would streamline analysis and make it easier to perform binding site analysis without repeatedly calling st.cell.find_nearest_pbc_position.

Thank you in advance for your time and consideration. I look forward to your feedback on this issue.

**Comment by wojdyr** [comment]
It's also ~2.8A in gemmi. The documentation shows two ways of calculating NearestImage:
```
>>> cra = mark.to_cra(st[0])
>>> st.cell.find_nearest_pbc_image(point, cra.atom.pos, mark.image_idx)
```
and
```
>>> st.cell.find_nearest_pbc_image(point, mark.pos, 0)
```
Both work, but you mixed the arguments.
In your example, the simplest way to calculate the distance is:
```py
for mark in ns.find_neighbors(ref_atom, min_dist=0.1, max_dist=CUTOFF):
    im = st.cell.find_nearest_pbc_image(ref_atom.pos, mark.pos, 0)
    print(im.dist())
```

NeighborSearch.Mark is what is stored in cell-lists – it exists before find_neighbors() is called.

**Comment by MichalGucwa** [comment]
You sir, are a gentleman. 
I sincerely apologize.

I changed my code according to your guidelines and it works.

Thank you for your help.

Best regards,
Michal Gucwa
