### ISSUE TITLE
FloatGrid resample_to missing?

### ISSUE THREAD

**Issue by Dialpuri** [project-gemmi/gemmi#343]
The Python documentation suggests the existence of a resample_to function [here](https://project-gemmi.github.io/python-api/gemmi.FloatGrid.html#resample_to). However, the source code and stubs suggest that it doesn't exist. 

Is this just residual documentation?

**Comment by wojdyr** [comment]
Yes, this function was removed in v0.7.0. Use `interpolate_grid()` instead.

Updating auto-generated documentation haven't worked after switching from pybind11 to nanobind. I'll sort it out at some point.
