### ISSUE TITLE
<parent>.add_<child> functions ivalidate references

### ISSUE THREAD

**Issue by sizmailov** [project-gemmi/gemmi#38]
Molecular `<parent>.add_<child>` functions apparently invalidate early stored references. While invalidation is common in C++ realm it might be quite surprising behavior to python users. Probably it deserves to be documented.

<details><summary>MRE</summary>

```python
import gemmi

pdb_string = """\
ATOM      1  N   LYS A  12       8.016  44.382 113.565  1.00 33.28           N
"""

st = gemmi.read_pdb_string(pdb_string)

model = st[0]
chain = model[0]
residue = chain[0]
atom = residue[0]

st.add_model(model)
# print(model) # uncomment to SIGSEGV

model.add_chain(chain)
# print(chain)  # uncomment to SIGSEGV

residue.add_atom(atom)
# print(atom)  # uncomment to SIGSEGV
```

</details>

**Comment by wojdyr** [comment]
Yes, that's a good point. I added a big warning.
