### ISSUE TITLE
PDB read: peptide residues are marked as EntityType.Unknown

### ISSUE THREAD

**Issue by sizmailov** [project-gemmi/gemmi#39]
A consequence of this issue is removal of  `TER` records in `.pdb` round trip which cannot be overwritten by any flags. 

<details><summary>MRE:</summary>

```python
import gemmi

st = gemmi.read_pdb_string("""\
ATOM      1  N   THR A   1     137.600 117.719 224.191  1.00107.30           N  
ATOM      2  CA  THR A   1     136.249 117.607 224.728  1.00121.14           C  
ATOM      3  C   THR A   1     136.208 116.647 225.914  1.00114.05           C  
ATOM      4  O   THR A   1     135.371 116.784 226.806  1.00103.45           O  
ATOM      5  CB  THR A   1     135.254 117.130 223.655  1.00127.19           C  
ATOM      6  H1  THR A   1     137.645 118.519 223.528  1.00107.30           H  
ATOM      7  H2  THR A   1     138.271 117.877 224.970  1.00107.30           H  
ATOM      8  H3  THR A   1     137.849 116.841 223.692  1.00107.30           H  
ATOM      9  HA  THR A   1     135.957 118.603 225.061  1.00121.14           H  
ATOM     10  N   ALA A   2     137.110 115.672 225.916  1.00117.01           N  
ATOM     11  CA  ALA A   2     137.250 114.762 227.047  1.00123.58           C  
ATOM     12  C   ALA A   2     138.018 115.456 228.166  1.00131.44           C  
ATOM     13  O   ALA A   2     137.725 115.279 229.359  1.00121.63           O  
ATOM     14  CB  ALA A   2     137.957 113.491 226.619  1.00112.08           C  
ATOM     15  H   ALA A   2     137.755 115.491 225.147  1.00117.01           H  
ATOM     16  HA  ALA A   2     136.260 114.489 227.414  1.00123.58           H  
ATOM     17  HB1 ALA A   2     138.054 112.823 227.475  1.00112.08           H  
ATOM     18  HB2 ALA A   2     137.379 112.999 225.837  1.00112.08           H  
ATOM     19  HB3 ALA A   2     138.948 113.737 226.237  1.00112.08           H  
TER
""")

print(st[0][0][0].entity_type)
print(st[0][0][1].entity_type)
```
output:
```
EntityType.Unknown
EntityType.Unknown
```
</details>

**Comment by wojdyr** [comment]
Normally the TER record marks the end of a polymer.
In the Amber files I remember that you had TER records also after ions, and generally TER was misused there. So if you specify ``split_chain_on_ter=True`` gemmi doesn't use TER to find out where the polymer ends.
You can call:

    st.setup_entities()

that uses heuristics to assign entity types (the term [entity type][1] is used in mmCIF-speak).
Calling it results in TER in the output file in your minimal example. I don't know how it will work for other examples.

[1]: http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_entity.type.html

**Comment by sizmailov** [comment]
Wow, that surprising. I was expecting `split_chain_on_ter=True` to only add extra chain breaks, I didn't expect it to turn polymers to unknown creatures (and parameter name doesn't imply it at all). Is there any rational behind this behavior? Can it be changed to recognize polymers by default? 

I've tested your suggestion (`st = gemmi.read_pdb("wbox.pdb",True);
st.setup_entities()`) on one of the amber simulation pdb files, it produced desired output, i.e. `600` polymer residues followed by `2312` water residues. 

[wbox.pdb](https://github.com/project-gemmi/gemmi/files/4705609/wbox.txt)

**Comment by wojdyr** [comment]
In correct pdb files it's the TER record that allows to tell apart polymer from ligands.
It becomes not possible if TER is misused, like in Amber files.

It's still possible to heuristically determine where the polymer ends, but it's not guaranteed to work in 100%, so it's not used by default.

**Comment by sizmailov** [comment]
You are right, `TER` residue is misused here and indicates end-of-molecule instead of end-of-chain. 

I would argue that defaults should correspond to most generic/common case. Whenever `split_chain_on_ter` option is active it's expected to read non-standard pdb file with altered meaning of `TER`. Therefore  user would required to call `st.setup_entities()` after altered `read_pdb` almost all the time.

If you are strictly against change of `split_chain_on_ter` effect on `pdb_read` then the least what can be done is documenting this option with all side effects it implies (and suggestion to apply `setup_entities()` afterwards) in public API reference  (in docstrings in python case).

Second issue than becomes evident is the desire to write TER records for all chains. Would it make sense to add such option to `write_pdb` (e.g. `ter_after_any_chain`)? Currently I have to assign everything to polymer, write pdb and revert original entity types to bypass it. I appreciate that you might not be highly interested in supporting various non-standard pdb formats.

**Comment by wojdyr** [comment]
I added option `chain_ignores_type` for this.
These features (this one and `split_chain_on_ter`) are intentionally undocumented, they are experimental.
I was thinking about naming the option `amber_ter`, but from what I understand the problem with AMBER input is that it can't detect where the chain have gaps and TER is required in all places where the consecutive residues are not bonded, except between waters. So if one was going to read standard PDB file and write a file for AMBER, a different TER-placing logic would be needed, with gap detection.

**Comment by sizmailov** [comment]
Thanks! 

I think AMBER mental model of what/how pdb file represents is different from standard and probably it's the source of all difficulties when we try to fit it in gemmi structure model. Mitigating this issue with hacky options to pdb read/write functions is good enough at the moment.

WRT to experimental features. I totally agree they are subject to change and it's totally fine. IMO it's still better to add doc with a big warning, rather let users guess what is what. If no one uses features you would never now how good/bad they are. Otherwise I don't see the point in exposing such shady experimental features.

Again, I really appreciate you efforts to steer me from using monkey-patched version of gemmi ;)
