### ISSUE TITLE
How can I cite gemmi?

### ISSUE THREAD

**Issue by murpholinox** [project-gemmi/gemmi#40]
How can I cite gemmi in a scientific publication?

Thanks

**Comment by wojdyr** [comment]
Thanks for asking.
We haven't published anything about gemmi yet. You could give this repository URL if it's possible in the journal.

**Comment by murpholinox** [comment]
Thanks.

**Comment by JBGreisman** [comment]
Following up on this -- @wojdyr is this a good way to cite `gemmi`? Are there additional authors that I should put?

```
@misc{gemmi,
  author = {Wojdyr, Marcin},
  title = {Gemmi - Library  for Structural Biology [Software]},
  year = {2021},
  howpublished = "\url{https://github.com/project-gemmi/gemmi}"
}
```

**Comment by wojdyr** [comment]
It reminds me that I should write a paper about Gemmi. This citation is good. Regarding additional authors, Keitaro is a frequent contributor, and to be future-safe it could be "Gemmi developers" or perhaps the author field could be skipped entirely. Actually, I don't know myself what would be the most proper citation :-) But thanks for asking.

**Comment by kvr2007** [comment]
My apologies for posting in a closed issue, but perhaps before the paper is out you could already register gemmi at Zenodo? This can be done relatively easy from the GitHub repo:

https://guides.github.com/activities/citable-code/

The good thing about Zenodo is that the software instantly gets a **doi** for citations. Furthermore, they implement a mechanism that would assign a doi to each version of the program.

I have already used gemmi in a publication, and there is another project in preparation. Gemmi is a real gem for PDB manipulation and analysis, so in my opinion it should get as many citations as possible! :)

**Comment by wojdyr** [comment]
Finally, we have a citation with DOI:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.04200/status.svg)](https://doi.org/10.21105/joss.04200)
