### ISSUE TITLE
Issue reading/writing mmcif file

### ISSUE THREAD

**Issue by jmp1985** [project-gemmi/gemmi#5]
Hi Marcin,

I am having an issue with Gemmi to read/write mmcif files and I was wondering if you could tell me what I am doing wrong. 

I have included a script that does the following:

1. Read cif file I obtained from the PDB into a gemmi structure
2. Write the structure to a new cif file
3. Read the new cif file back into gemmi in the same way.

```
import gemmi
    
def test(in_filename, out_filename):
    
    # Read the structure
    structure = gemmi.read_structure(in_filename)

    # Write the structure
    structure.make_mmcif_document().write_file(out_filename)

if __name__ == '__main__':
    test("4v5d.cif", "out1.cif")
    test("out1.cif", "out2.cif")
```

When I do this, I get the following error:

```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 36, in <module>
    test("out1.cif", "out2.cif")
  File "test.py", line 6, in test
    structure = gemmi.read_structure(in_filename)
RuntimeError: out1.cif:149:0(2233): Wrong number of values in the loop



```

I have attached the script and the initial cif file here. [file_and_script.zip](https://github.com/project-gemmi/gemmi/files/3661981/file_and_script.zip)

Thanks in advance for your help!

**Comment by wojdyr** [comment]
Hi James,
it's a bug in writing mmCIF file that got somehow overlooked, probably for many months. I've fixed it now.
Thanks for reporting it.

**Comment by jmp1985** [comment]
Thanks Marcin!
