### ISSUE TITLE
gemmi validate: use of quotes

### ISSUE THREAD

**Issue by CV-GPhL** [project-gemmi/gemmi#52]
When checking against a controlled vocabulary, the list of allowed values is given as a plain, comma-separated list. This makes it very hard to read and doesn't take into account that the allowed values themselves might have a comma (if they are character items).

It would be nice to get (shortened)

some.cif:16 in data_1: _pdbx_diffrn_data_section_contents.content_type: ''X-Ray structure factor amplitudes(+)'' is not one of:
&nbsp;&nbsp;"X-ray structure factor amplitudes"
&nbsp;&nbsp;"X-ray structure factor intensities, unmerged"

(each allowed value on new line) instead of the current one-liner:

some.cif:16 in data_1: _pdbx_diffrn_data_section_contents.content_type: ''X-Ray structure factor amplitudes(+)'' is not one of: X-ray structure factor amplitudes, X-ray structure factor intensities, unmerged.

**Comment by wojdyr** [comment]
OK, I added new lines.

Note: I was implementing validation with DDL2 dictionaries in 2017 and haven't finished it, because I didn't see much use for it.
Here, the enumeration values are compared as case-sensitive, although some of them are not.
And many checks are not performed at all.
