### ISSUE TITLE
gemmi validate: stopping early?

### ISSUE THREAD

**Issue by CV-GPhL** [project-gemmi/gemmi#53]
Does the validation only ever report the first instance of an issue for a given item? E.g. I know that a mmCIF file has several new _pdbx_diffrn_data_section_contents.content_type values, but only ever get one problem report back.

Is that intential or a buglet?

**Comment by wojdyr** [comment]
Looking into it was intentional:
https://github.com/project-gemmi/gemmi/blob/6f2feb4c026cbcb3ec4ea55175b2b14d146b9157/src/validate.cpp#L415
I must have added it because one loop generated a lot of similar messages.

**Comment by wojdyr** [comment]
btw now gemmi-validate checks also regex expressions and is aware of case sensitivity.
