### ISSUE TITLE
Setting spacegroup of gemmi FloatGrid

### ISSUE THREAD

**Issue by JBGreisman** [project-gemmi/gemmi#55]
`gemmi.FloatGrid` seems to have a method for setting its corresponding unit cell (`FloatGrid.set_unit_cell()`), but there is not a corresponding method for setting the grid's spacegroup. This seems useful for being able to get the correct ASU mask from the `FloatGrid.asu()` method. 

This is the current behavior:
```python
grid = gemmi.FloatGrid(100, 100, 100)
grid.spacegroup = gemmi.SpaceGroup(19)
print(grid.spacegroup)
```
returns:
```
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-142-5698f3495619> in <module>
----> 1 print(grid.spacegroup)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 20: invalid start byte
```

Is there a way to set the spacegroup for a `FloatGrid` object that was not instantiated directly from a call to `gemmi.transform_f_phi_grid_to_map()`?

Thanks,
Jack

**Comment by wojdyr** [comment]
Hi Jack,
`grid.spacegroup = ...` is the intended way to set it. I don't know why you get the error.
I didn't manage to reproduce it:
```
>>> import gemmi
>>> grid = gemmi.FloatGrid(100, 100, 100)
>>> grid.spacegroup = gemmi.SpaceGroup(19)
>>> print(grid.spacegroup)
<gemmi.SpaceGroup("P 21 21 21")>
```

**Comment by JBGreisman** [comment]
You're correct -- this turned out to be a version issue on my end. This seems to be fine in the latest gemmi 0.4.2 version:

```
In [1]: import gemmi

In [2]: gemmi.__version__
Out[2]: '0.4.2'

In [3]: grid = gemmi.FloatGrid(100, 100, 100)

In [4]: grid.spacegroup = gemmi.SpaceGroup(19)

In [5]: grid.spacegroup
Out[5]: <gemmi.SpaceGroup("P 21 21 21")>
```
However, I had used `conda` to install gemmi previously, and the latest version on the conda-forge channel seems to be 0.4.1. That version had this issue:

```
In [1]: import  gemmi

In [2]: gemmi.__version__
Out[2]: '0.4.1'

In [3]: grid = gemmi.FloatGrid(100, 100, 100)

In [4]: grid.spacegroup = gemmi.SpaceGroup(19)

In [5]: print(grid.spacegroup)
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-5-5698f3495619> in <module>()
----> 1 print(grid.spacegroup)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 20: invalid start byte
```
I'll close this issue because it seems to be resolved in the latest release on `pip`.

**Comment by wojdyr** [comment]
I tried it with gemmi from conda-forge (python 3.7 on Linux), but it worked for me. It must be something specific to version or system.
I'll do a new release soon. Hopefully it will get into conda-forge and perhaps it will fix this problem.
