### ISSUE TITLE
Space group 141 error

### ISSUE THREAD

**Issue by seta667** [project-gemmi/gemmi#56]
I'm quite new to gemmi and crystal summetry, so I apologize in advance is the following issue is just a non-sense but, when I retrieve retrieved sym_ops operations using gemmi for space group 141:
```
ops = gemmi.find_spacegroup_by_number(141).operations()
sym_ops = ops.sym_ops

```
Retrieved operations are:
  x,y,z
  -y,x+1/2,z+1/4
  -x+1/2,-y+1/2,z+1/2
  y+1/2,-x,z+3/4
  x,-y+1/2,-z+1/4
  -y,-x,-z
  -x+1/2,y,-z+3/4
  y+1/2,x+1/2,-z+1/2
  -x,-y+1/2,-z+1/4
  y,-x,-z
  x+1/2,y,-z+3/4
  -y+1/2,x+1/2,-z+1/2
  -x,y,z
  y,x+1/2,z+1/4
  x+1/2,-y+1/2,z+1/2
  -y+1/2,-x,z+3/4

However, those operations do not match with those listed for instance in the bilbao crystallographic database (https://www.cryst.ehu.es/cgi-bin/cryst/programs/nph-wp-list):

(x,y,z)	(-x+1/2,-y,z+1/2)	(-y+1/4,x+3/4,z+1/4)	(y+1/4,-x+1/4,z+3/4)
(-x+1/2,y,-z+1/2)	(x,-y,-z)	(y+1/4,x+3/4,-z+1/4)	(-y+1/4,-x+1/4,-z+3/4)
(-x,-y,-z)	(x+1/2,y,-z+1/2)	(y+3/4,-x+1/4,-z+3/4)	(-y+3/4,x+3/4,-z+1/4)
(x+1/2,-y,z+1/2)	(-x,y,z)	(-y+3/4,-x+1/4,z+3/4)	(y+3/4,x+3/4,z+1/4)

I was wondering if this is an error, as my calculation runs smoothly with bilbao's but not gemmi operations, or I am missing something important.

Thanks very much in advance.

**Comment by wojdyr** [comment]
This spacegroup has two commonly-used settings that are denoted as:
I 41/a m d:1
I 41/a m d:2
They correspond to the first and the second list of operations in your question.
You may also compare it with https://cci.lbl.gov/cctbx/explore_symmetry.html
