### ISSUE TITLE
mmcif empty loop

### ISSUE THREAD

**Issue by keitaroyam** [project-gemmi/gemmi#58]
Gemmi stops parsing mmcif file when encountered no values in loop. Below is the example from Refmac's output. This may be a violation of cif format and Refmac will be fixed, but can gemmi support reading this?

```
...
loop_
   _chem_comp_tor.comp_id
   _chem_comp_tor.id
   _chem_comp_tor.atom_id_1
   _chem_comp_tor.atom_id_2
   _chem_comp_tor.atom_id_3
   _chem_comp_tor.atom_id_4
   _chem_comp_tor.value_angle
   _chem_comp_tor.value_angle_esd
   _chem_comp_tor.period
var_1     FES      FE1  S2   FE2  S1          0.000      20.000   1
var_2     FES      FE2  S2   FE1  S1          0.000      20.000   1
var_3     FES      FE2  S1   FE1  S2          0.000      20.000   1
#
loop_
   _chem_comp_chir.comp_id
   _chem_comp_chir.id
   _chem_comp_chir.atom_id
   _chem_comp_chir.volume_flag
   _chem_comp_chir.volume_three
loop_
   _chem_comp_chir_atom.comp_id
   _chem_comp_chir_atom.chir_id
   _chem_comp_chir_atom.atom_id
#
data_comp_MA6
....
```

**Comment by dkratzert** [comment]
CIF files from SHELXL prior to version 2017/2 also had this problem. So, good to be fixed...

**Comment by wojdyr** [comment]
yes, that's invalid CIF format and there was an exception for empty loops, but it worked only if the loop was followed by another loop or EOF. Now I made it more general and the file should parse.

Is _chem_comp_chir_atom a new category? I don't see it in the monomer library.

**Comment by wojdyr** [comment]
Daniel: it still won't work if the empty loop is followed by

    _tag value

because then _tag is interpreted as another tag in the loop header.
This would be hard to disambiguate.

**Comment by dkratzert** [comment]
OK, thanks

**Comment by keitaroyam** [comment]
It worked, thank you very much!
_chem_comp_chir_atom seems a PDBx/mmCIF record, but I don't know why it is there. I am asking Garib about this.
