### ISSUE TITLE
question about SpaceGroup GroupOp order

### ISSUE THREAD

**Issue by bodomartin** [project-gemmi/gemmi#7]
Hi,

first of all thank you for this great lib. 

I have a question about the order of operations (triplets) e.g. for P 1 21/n 1 gemmi gives:
x,y,z (identity)    -x,-y,-z   -x+1/2,y+1/2,-z+1/2   x+1/2,-y+1/2,z+1/2

which is fine but not in the order given by the tables, where the order would be 
(e.g. http://img.chem.ucl.ac.uk/sgp/large/014hy1.htm)
x,y,z   -x+1/2,y+1/2,-z+1/2 -x,-y,-z x+1/2,-y+1/2,z+1/2 

so how can I get the order corresponding to the tables? 
(this may be an obvious/stupid question, but I am not a crystallographer)

Regards 

bm

**Comment by wojdyr** [comment]
I don't know. If operations in Jeremy Cockcroft's tables or in International Tables of Crystallography are ordered according to some rules, I could try to use these rules in gemmi.
But perhaps the order is just random, I don't know.

**Comment by bodomartin** [comment]
hmm the obvious answer would be that the order is determined by the successive application of the symmetry generators ; in this case 2_1 = is a 180° (twofold) rotation followed by a translation of 1/2 of the lattice vector, so the second entry must in fact be -x+1/2,y+1/2,-z+1/2 in this case.

In the documentation you state that gemmi derives its symmetry operators from the HM symbols, so the order should be correct when generating? - or is there a sorting step in between

**Comment by wojdyr** [comment]
Operations are derived from Hall symbols. H-M `P 1 21/n 1` corresponds to Hall symbol `-P 2yn`,
which encodes two generators:
    -x,-y,-z
    -x+1/2,y+1/2,-z+1/2
The first one is encoded by `-`. If I'd put the `-x,-y,-z` generator as the last one I'd get the same order for this space group.
This is a trivial change that I can do. But I don't know if helps with other space groups.

**Comment by wojdyr** [comment]
I did this change. For P 1 21/n 1 the order is now the same as on the linked page. I didn't check other space groups.

**Comment by bodomartin** [comment]
thanks, but I would ask you to revert the change. I have tested with spglib, which gives the same order as gemmi (before modification). I think I found that the spacegroups are decomposed into the cosets under the translation group ... I need to figure out exactly how to do this, maybe later I can provide a function for getting the ITA order.

**Comment by wojdyr** [comment]
But on the other hand the new order is the same as in [cctbx][1] and [CCP4 syminfo.lib][2].

[1]: https://cci.lbl.gov/cctbx/explore_symmetry.html
[2]: http://www.ccp4.ac.uk/html/symlib.html

**Comment by bodomartin** [comment]
ok. Have you tested for other space groups as well? 
I also suspect is is just a question of how the data is stored (triplet form for all or generated)
but the symmetry operations order must be defined somehow (the cif field _symmetry_equiv_pos_as_xyz should be the same always no matter which program generated the cif file). .. if I find out something I will report back. Thanks

**Comment by wojdyr** [comment]
I don't think that the order matters. The coreCIF spec only requires that x,y,z has id=1. Apart from this the order of _symmetry_equiv_pos_as_xyz is not specified.
