### ISSUE TITLE
Issue with find_shortest_path

### ISSUE THREAD

**Issue by glycojones** [project-gemmi/gemmi#78]
find_shortest_path in chemcomp.hpp fails to find shortest path between ("C4", "O6", {"C5", "C6"}) and ("C5", "C2", {"C6", "O6"}) for acedrg-generated KDA, KDO, KDR, KME and KOT. Fix not urgent - can use workaround for now.

**Comment by wojdyr** [comment]
Hi Jon, sorry about it. It's fixed now.

**Comment by glycojones** [comment]
No worries, I'll test ASAP.
