### ISSUE TITLE
cif.read() raises exception by a certain file

### ISSUE THREAD

**Issue by lavakin** [project-gemmi/gemmi#81]
Hi,
I am trying to parse a cif file 1ue4. My code looks like this:
```python
doc = cif.read("1ue4.cif")
```
By other cif files it works normally, but by this file it raises an exception: `Wrong number of values in the loop `

(In the previous version it worked.)

**Comment by wojdyr** [comment]
Is this file downloaded directly from the PDB? I can't reproduce it.

    >>> cif.read('/home/wojdyr/Downloads/1ue4.cif')
    <gemmi.cif.Document with 1 blocks (1UE4)>
