### ISSUE TITLE
Memory error on superimposition

### ISSUE THREAD

**Issue by lpravda** [project-gemmi/gemmi#86]
Hi @wojdyr , I tried the superposition algorithm from python, but it seems to crash often.

## My configuration
* MacOS Big Sur / Red Hat 7.4
* gemmi: 0.4.4 from conda-forge
* Python 3.7.8

## Data
* https://www.ebi.ac.uk/pdbe/entry-files/download/2vta_updated.cif
* https://www.ebi.ac.uk/pdbe/entry-files/download/6q49_updated.cif

## minimal code to reproduce
```python
 import gemmi

 x = gemmi.read_structure('2vta_updated.cif')[0]['A'].get_polymer()
 y = gemmi.read_structure('6q49_updated.cif')[0]['A'].get_polymer()

 r = gemmi.calculate_superposition(x, y, gemmi.PolymerType.PeptideL, gemmi.SupSelect.CaP) # this line fails
```

What I could get out if that is:
* on Mac: `[1]    25560 segmentation fault  `
* on LInux: I got  `MemoryError: std::bad_alloc`

there is additional line of code that crashes (again segmentation fault) I could find in the documentation and that is: `x.check_polymer_type()`, that is why I use `gemmi.PolymerType.PeptideL` in the code.

Interestingly, when I use archive files (https://www.ebi.ac.uk/pdbe/entry-files/download/2vta.cif and https://www.ebi.ac.uk/pdbe/entry-files/download/6q49.cif) I dont get the memmory error, but nothing is computed, only thing I can see is message `More than 50 iterations needed!` So my natural question is how can I increase this limit and is there anything I can do to provide more info so that you guys can track down the root of the problem? 

Thank you for looking into this!

**Comment by wojdyr** [comment]
Fixed. The problem was that calling `.get_polymer()` didn't prevent garbage collector from discarding Chain and Structure. You may either update gemmi or use a workaround:

    a1 = gemmi.read_structure('2vta_updated.cif')[0]['A']
    x = a1.get_polymer()
    a2 = gemmi.read_structure('6q49_updated.cif')[0]['A']
    y = a2.get_polymer()

Thanks for reporting it.

**Comment by lpravda** [comment]
This is perfect, thank you for a prompt fix! I'll updated my instance from git. Any estimation when this is going to be available in conda-forge? The installation from wheel for some reason takes forever.

**Comment by wojdyr** [comment]
Usually it's on conda-forge soon after release, and the next release should also be soon, probably this week.
