### ISSUE TITLE
segfault on badly formed mmCIF files

### ISSUE THREAD

**Issue by jsoerensen** [project-gemmi/gemmi#9]
We've recently gotten some segfaults reading certain mmCIF files. I've attached an example here. 
[6j40.cif.txt](https://github.com/project-gemmi/gemmi/files/3932964/6j40.cif.txt)

We see this in the trace:
terminate called after throwing an instance of 'tao::pegtl::parse_error'
what(): string:107819:0(9901474): Wrong number of values in the loop

It seems to be due to badly formed MMCIF files, because in some cases when we download a revised version of those same MMCIF files the problem goes away.

Is there a way we can safeguard the parser to avoid this?

**Comment by wojdyr** [comment]
Maybe only part of the file was downloaded? It ends with:
```
M  13 68  ASN 68  68  68  ASN ASN O  . n 
M  13 69  SER 69  69  69  SER SER O  . n 
M  13 70  LYS 70  70  70  LYS LYS O  . n 
M  1
```
Do you use it from C++ or Python?

**Comment by jsoerensen** [comment]
This was in C++.
Yes it does look like the file was partial, we are looking into why the downloader we are using is having this problem. 
If the file is partial is there a way to catch this problem and not segfault, but instead return false with a warning or throw?

**Comment by wojdyr** [comment]
yes:

    catch (tao::pegtl::parse_error& e)

or more generally:

    catch (std::runtime_error& e)
