### ISSUE TITLE
Question about as_json

### ISSUE THREAD

**Issue by frozenfas** [project-gemmi/gemmi#92]
Hello, I would like to ask a question about the as_json method.  I believe the default behaviour is for it to lowercase the names (line 24 in to_json.hpp) but I was wondering if there is any way in python to be able to set this behaviour to false? I see there is the mmjson value but this also changes other settings? Thanks in advance for any tips advice you can provide.

**Comment by wojdyr** [comment]
ok, I added such an option (`lowercase_names=False`)

**Comment by frozenfas** [comment]
Thanks so much I will try this out.
