### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by merkys** [project-gemmi/gemmi#99]
README.md lists MPLv2 and LGPLv3, setup.py lists only MPLv2, and LICENSE.txt contains the text of MPLv2.

Is LGPLv3 really applicable, or is it just a leftover in README.md? In that case, README.md should be updated to reflect the current licensing situation.

**Comment by wojdyr** [comment]
If you prefer LGPL, you may use gemmi under the terms of LGPL v3.
The license text is not included, because having three license files (the text of LGPL v3 is in two files) would be confusing.

**Comment by merkys** [comment]
Thanks for clarification. I saw LGPL only in README.md, so I thought that was a typo. Maybe setup.py could also have LGPLv3 classifier to make it more visible?

Usual practice for dual-licensed projects seems to have two license files, like LICENSE-MPL.txt and LICENSE-LGPL.txt.

**Comment by wojdyr** [comment]
OK, I'll add a comment in setup.py to confirm that there is an option of using gemmi under the terms of LGPL 3 license.
But do you see any reason to prefer LGPL over MPL?

**Comment by merkys** [comment]
> OK, I'll add a comment in setup.py to confirm that there is an option of using gemmi under the terms of LGPL 3 license.

Thanks.

> But do you see any reason to prefer LGPL over MPL?

No, I personally do not. I am just making sure I understand licensing options right.
